Dockerfile
8.12 was released on 2016-01-02
=> Upgrade to use sentry 8.12

Dockerfile
8.13 was released on 2016-02-01
=> Upgrade to use sentry 8.13

Dockerfile, sentry.conf.py
`sentry.conf.py` is pulled from https://github.com/getsentry/docker-sentry/tree/master/8.17
=> Update to 8.17

LICENSE
=> meta(license): Add Apache 2.0 license to the project

README.md
=> meta(readme): Update minimum docker-compose version

.dockerignore, .travis.yml, install.sh, test.sh
Helps avoid situations like #187.
=> ci(travis): Enable smoke tests with TravisCI

README.md
=> docs(readme): Update readme for the install script

.env.example, .travis.yml, Dockerfile, docker-compose.yml, test.sh
This patch adds the optional IMAGE env variable to set the base
image and adds nightly builds to Travis CI.
=> feat(nightlies): Add ability to build from nightlies

Makefile
closes #214
Signed-off-by: Jamin W. Collins <jamin.collins@gmail.com>
=> -e needed for color codes

README.md, install.sh
Required after #211. Fixes #213.
=> fix: Update minimum Docker version

Makefile
=> fix(Makefile): Bring back the new lines from messages

.env.example, .travis.yml, Dockerfile
=> fix(Dockerfile): Fix default IMAGE missing

.travis.yml, Dockerfile, docker-compose.yml, install.sh
=> fix(install): Fix invalid reference format again

install.sh
=> fix(build): make version checker more robust in install

install.sh
This should fix the GCB failures.
=> fix(install): Don't run migrations in interactive mode

install.sh
- escape entrypoint parameter character
close #329
=> fix(install): support for Windows and Git Bash

install.sh
=> fix(install): Fix secret key gen on BSD

install.sh
Fixes #334.
This is a workaround until getsentry/sentry#16353 gets merged.
=> fix(data-migration): Make sure to chown the /data folder on sentry

README.md
=> meta(readme): Update docs and chat links in readme

install.sh
As asked by @BYK on #358, something like that can do the trick ;)
=> Check SSE4.2 compatibility before installation

sentry/sentry.conf.example.py
=> fix(config): Enable http-chunked-input for UWSGI

README.md
=> docs(upgrade): Add note regarding min Sentry 9.1.2 requirement

docker-compose.yml
These became obsolete after getsentry/snuba#825
=> feat(snuba): Remove redundant UWSGI settings

docker-compose.yml
Add missing restart policy unless-stopped for symbolicator-cleanup service
=> Add missing restart policy unless-stopped

docker-compose.yml
=> upgrade(clickhouse): Use 19.17 as it seems to be fixing some issues

install.sh
This patch does two things:
1. Separate creating of Relay credentials from syncing them to Sentry config
2. Has a more flexible Relay credentials check and sync: look for the quoted public key in the config file, if it is there, assume this must be correctly set as it is very unlikely to have that random key in a different context with quotes around. The second one is to allow having other whitelisted relay keys by using an append method when adding the new key.
=> ref(relay): More robust Relay credentials setting

README.md
=> Updating documentation link

install.sh
This PR disables checking for the SSE4.2 flag, which may not be present if the server is running in a VM even if SSE4.2 is in fact available to use (ClickHouse/ClickHouse#20). The KVM check was obtained from a [comment](https://github.com/ClickHouse/ClickHouse/issues/20#issuecomment-226849297) in that issue.
If SSE4.2 is not actually available in the VM, then the installation script may fail in an unpredictable way. Perhaps we can add a keyword argument to the script to let the user decide if they want to skip the check.
=> fix(install.sh): skip checking for sse4 2 flag if kvm was detected

docker-compose.yml
=> feat(kafka): Increase max message size

install.sh
=> fix(zookeeper): Temp ZK fix should run in detached mode

sentry/config.example.yml
* added new default going forward uncommented
* added link to future guide
* added support for new signing-secret
* slight rejig to config
=> fix(slack): Point to newer docs, better defaults

test.sh
Running Docker on the host network is not supported on GCB, which is breaking our builds over at getsentry/sentry. This patch removes the use of sentry-cli and does a manual `curl` request to create the test event.
=> fix(test): Don't use sentry-cli for test event

docker-compose.yml
Needed for Performance to work (see #586).
Depends on #593. Fixes #588.
=> feat(snuba): Add transactions consumer

install.sh
This reduces downtime for users with custom Dockerfiles. Fixes #607.
=> feat: Only stop the cluster after building images

install.sh
h/t https://unix.stackexchange.com/a/79077
Fixes #622, cf. #600 
cc: @NullIsNot0
=> fix(env): Read and set .env in install.sh, portably

install.sh
=> fix(install): TSDB migration should not create invalid config file

.github/workflows/test.yml
Pretty sure I've got this right, based on both reading docs and experimenting ... assuming this is desired behavior?
Part of #627, addresses https://github.com/getsentry/onpremise/pull/634#discussion_r474287108.
=> ci(gha): Fine-tune GHA event bindings

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
https://app.asana.com/0/1169344595888357/1190341230301209/f
/cc @PeloWriter
=> meta(issues): Add issue templates

README.md, install.sh
=> install: Add flag to skip create user prompt during install

.editorconfig, .github/workflows/release.yml, cron/entrypoint.sh, install.sh, relay/config.example.yml, test.sh
EditorConfig based on conversation in https://github.com/getsentry/onpremise/pull/615#discussion_r477338006, and with the indentation fixes.
This PR will probably conflict with everything, but at least the code is a little bit more consistent :-D
=> EditorConfig and indentation fixes

install.sh
=> fix(ingest-consumer): Create the missing Kafka topics

install.sh
=> fix(docker): Lower docker version to 19.03.6

install.sh
Probably this is not needed anymore after https://github.com/getsentry/sentry/pull/20984 is merged, but just in case
=> fix(install): Check that all ingest topics exist

sentry/config.example.yml, sentry/sentry.conf.example.py
Follow up to getsentry/sentry#21041
=> ref(config): Move GitHub config over to config.yml

sentry/sentry.conf.example.py
Addresses https://forum.sentry.io/t/advanced-search-access-in-onpremise-install/11736?u=byk
=> feat(search): Enable advanced search for self-hosted

clickhouse/config.xml, docker-compose.yml
fixes #701
Followed the documentation but did not tested the result.
=> fix(clickhouse): default logger level set to information

.github/workflows/release.yml
=> ci(release): fix a couple typos 🐭

README.md
After following the instructions on this repo for upgrading, and breaking my installation, I thought it might be helpful to others if these instructions were clarified a little.
=> Clarify upgrade process

.github/workflows/lock.yml
Per https://github.com/getsentry/sentry/pull/22754#discussion_r544690140.
=> meta: Pin lock-threads, crank frequency to test

.github/workflows/lock.yml
https://github.com/getsentry/onpremise/runs/1572138916?check_suite_focus=true#step:2:1
=> meta: Pin works, dial back to daily

.github/workflows/lock.yml
Pursuant to https://github.com/getsentry/.github/issues/11.
=> meta: Fork lockbot for security

.github/workflows/test.yml
Haven't gotten a clean test run yet over on #766. Time to investigate ...
=> Unfrobulate CI

.github/workflows/lock.yml, .github/workflows/release.yml, .github/workflows/stale.yml, .github/workflows/test.yml
https://github.com/getsentry/onpremise/pull/811#discussion_r557519591
=> meta: Capitalize action names

.github/workflows/test.yml
This should keep the pool open.
=> ci(test): Limit concurent jobs to 1

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/enforce-issue-template.yml, .github/workflows/validate-new-issue.yml
First crack at https://github.com/getsentry/.github/issues/8.
https://github.com/chadwhitacre/chadwhitacre-testing-nothing-to-see-here/issues/25#issuecomment-759776549
=> Validate new issues against templates

.github/workflows/test.yml
=> ci(test): Even larger pools

.github/workflows/test.yml, install.sh, test.sh
GHA provides nice UI using [this syntax](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#grouping-log-lines), which isn't _too_ ugly in raw logs.
(Baby step towards https://github.com/getsentry/onpremise/issues/795, btw.)
=> Add some structure to logging with ::group::

.github/workflows/validate-new-issue.yml
=> Deploy action: validate-new-issue.yml

.github/workflows/validate-new-issue.yml
I are a bot. 🤖
https://github.com/getsentry/.github/blob/f51bb175b187a48f54f699740cce8acd85c09e92/.github/workflows/validate-new-issue.yml
=> meta(gha): Deploy action validate-new-issue.yml

.github/workflows/test.yml, install.sh, install/_lib.sh, install/_test_setup.sh, install/docker-aliases.sh, install/geoip.sh, install/relay-credentials-test.sh, install/relay-credentials.sh
Step towards #795, introduces more fine-grained testing (not wired to CI yet tho).
=> Refactor relay config

.github/workflows/test.yml, install.sh, install/_lib.sh, install/_test_setup.sh, install/create-docker-volumes-test.sh, install/create-docker-volumes.sh, install/geoip.sh, install/relay-credentials-test.sh, install/relay-credentials.sh
Part of #795, follow-on to #900.
=> Factor out volume creation

.github/workflows/test.yml, install/_test_setup.sh, install/geoip-test.sh
Starting to drift from the core of #795 here ... I starting looking at stubbing out dcr somehow to test the conf side of geoip, but decided to pull back to refocus on #795.
=> Add a partial test for geoip

install.sh
Didn't surface in CI ... for obvious reasons. ;)
=> Fix a regression with unset envvars

docker-compose.yml
=> fix: Ensure snuba cleanup job runs on the correct storage

docker-compose.yml
=> fix: Add missing snuba transactions clean up service

install/set-up-zookeeper.sh
Fixes #951, a regression introduced with #908.
=> fix: Fix incorrect zookeeper mount path

.github/workflows/issue-routing-helper.yml
I are a bot, here to deploy [issue-routing-helper.yml](https://github.com/getsentry/.github/blob/57bd472f2ba4a4fe2b6273d2efef592786e7e664/.github/workflows/issue-routing-helper.yml). 🤖
=> meta(gha): Deploy action issue-routing-helper.yml

.gitattributes
=> ci: Add .gitattributes file to exclude unnecessary files from repo zips

.craft.yml, CHANGELOG.md
@billyvg has a breaking change coming up soon so let's use this as an opportunity to add a changelog. This changelog will only capture important announcements (such as this breaking change over at Sentry) and changes in this repo for now.
=> meta: Add some changelog

test.sh
But will this work on Ubuntu? 🙈
=> Port test.sh to macOS

.github/workflows/test.yml, .gitignore, certificates/.gitignore
Addresses this: https://forum.sentry.io/t/configure-gitlab-self-signed-ssl-certificate/14766/3?u=byk
=> feat: Have an empty certificates folder ready

.github/workflows/test.yml, install/_min-requirements.sh, install/check-minimum-requirements.sh
Refs #1061, refs #1062, refs #1063.
=> ci: Test with the required minimum docker-compose

CHANGELOG.md
=> docs(changelog): Add missing entries for docker-compose changes

CHANGELOG.md, docker-compose.yml
=> fix(healthcheck): Increase retries to 5

.github/ISSUE_TEMPLATE/config.yml
Part of #1151, follow-up to #1159, meant to include this there but failed to.
=> Remove link to forum

.env, docker-compose.yml
This is a follow up to https://github.com/getsentry/self-hosted/pull/1241.
(Particularly https://github.com/getsentry/self-hosted/pull/1241#issuecomment-1006628149 :P)
=> Make healthcheck variables configurable in .env

.github/workflows/test.yml, install/create-kafka-topics.sh, install/relay-credentials.sh
Reverts getsentry/self-hosted#1251
We're seeing a failure on an internal CI build that seems to be caused by this, still investigating ...
=> Revert "Add CI compose version 1.29.2 / 2.2.3"

.github/workflows/test.yml, install/create-kafka-topics.sh, install/relay-credentials.sh
=> Add CI compose version 1.29.2 / 2.0.1 / 2.2.3

install/ensure-relay-credentials.sh
=> Pull relay explicitly to avoid garbage in creds

install/turn-things-off.sh
Aims to fix https://github.com/getsentry/self-hosted/issues/1178.
=> Turn off containers under old name as well

.github/ISSUE_TEMPLATE/problem-report.yml
As there is not a template for discussions yet, let's improve this at least?
First brought up here: https://github.com/getsentry/self-hosted/discussions/1496
=> Get more data from users in issue templates

install/_lib.sh, install/error-handling.sh
Reverts getsentry/self-hosted#1753
=> Revert "Enforce error reporting for self-hosted"

.github/workflows/release.yml, .github/workflows/test.yml
=> Update to actions/checkoutv3 to address upcoming github deprecations

.github/workflows/test.yml
https://github.com/getsentry/action-self-hosted-e2e-tests/pull/3
=> Pick up CI bugfix

install/install-wal2json.sh
Kludge to fix https://github.com/getsentry/self-hosted/issues/1899.
=> Fix wal2json flakiness

sentry/sentry.conf.example.py
4th of 4:
- https://github.com/getsentry/sentry/pull/45400
- https://github.com/getsentry/sentry/pull/45401 
- https://github.com/getsentry/getsentry/pull/9712 
- https://github.com/getsentry/self-hosted/pull/2010 (you are here)
Related to https://github.com/getsentry/sentry/issues/45197
=> ref(replays): Remove the session-replay-ui flag

docker-compose.yml
Related issues, pr
- https://github.com/getsentry/snuba/issues/3696
- https://github.com/getsentry/snuba/pull/3697
- https://github.com/getsentry/snuba/pull/3804
Add snuba sessions subscription to self-hosted. cc @lynnagara 
=> feat(snuba): Add snuba sessions subscription service

.github/ISSUE_TEMPLATE/problem-report.yml
Closes https://github.com/getsentry/self-hosted/issues/2078
=> Fix command to get docker compose version in problem report template

scripts/_lib.sh
This shouldn't be here. 
Found on Sentry: https://self-hosted.getsentry.net/organizations/self-hosted/issues/386/?project=3&query=is%3Aunresolved&referrer=issue-stream
=> Remove clean function testing line

docker-compose.yml, sentry/sentry.conf.example.py
Closes #2068 
Users should only need to add `OPENAI_API_TOKEN=<their token value>` to their `.env.` or `.env.custom` file. That's about it. It works magically.
A screenshot from my self-hosted instance:
=> feat: add suggested fix feature

sentry/sentry.conf.example.py
This will enable CSP for self-hosted users. Follows
https://github.com/getsentry/sentry/pull/47980
=> Add settings for enabling CSP to config file

docker-compose.yml
Talked to SNS team, and this might solve the issue [here](https://github.com/getsentry/self-hosted/issues/1894) 🤞
=> Add no strict offset reset options to consumers

docker-compose.yml
Fixes security issues: https://raw.githubusercontent.com/redis/redis/6.2/00-RELEASENOTES
Last update: b1fda9a55203e3f28a3d02e1056213449b7cff45
=> Update redis to 6.2.12

docker-compose.yml
Bumps 3 years of patch releases !
https://github.com/memcached/memcached/wiki/ReleaseNotes
Previous update: f5411170ac0fb7f5ce8e7f5a1b21b16cbb176937
=> Update memcached to 1.6.21

_unit-test/error-handling-test.sh, _unit-test/snapshots/sentry-envelope-12345123451234512345123451234512, _unit-test/snapshots/sentry-envelope-f73e4da437c42a1d28b86a81ebcff35d, install/error-handling.sh
Turns out we weren't fingerprinting properly. We were sending our custom hash as the `event_id` and not as a `fingerprint` array.
=> Fix error fingerprinting

.github/workflows/test.yml
picks up https://github.com/getsentry/action-self-hosted-e2e-tests/pull/13
=> Bump self-hosted e2e action commit sha

clickhouse/config.xml
Fixes https://github.com/getsentry/self-hosted/issues/2364
=> Reduce logs coming from clickhouse

.github/workflows/test.yml
Too flaky, make it twice per day
=> Decrease frequency of e2e tests

_integration-test/ensure-backup-restore-works.sh, scripts/_lib.sh
Closes getsentry/team-ospo#184
=> feat(backup): Support new backup script

README.md
Closes https://github.com/getsentry/self-hosted/issues/2438
=> Update outdated install option in README

.github/workflows/fast-revert.yml
used in [sentry](https://github.com/getsentry/sentry/blob/master/.github/workflows/fast-revert.yml), would be nice to have it here
=> Add fast revert GH workflow

docker-compose.yml
A part of https://github.com/getsentry/self-hosted/issues/2200
=> Remove sessions infra

install/check-latest-commit.sh
=> ref: use `git branch --show-current` instead of sed

CHANGELOG.md
mostly to validate the new sentry dockerfile
=> ref: fix a typo

README.md
As Sentry has grown, our microservices are now demanding more resource usage
https://github.com/getsentry/self-hosted/issues/2574
=> Bump minimum ram usage

.github/ISSUE_TEMPLATE/release.yml
=> Tweak the template now that we can see it

.github/workflows/test.yml
Run tests only on getsentry repository.
=> Run tests only on getsentry repository

docker-compose.yml, sentry/sentry.conf.example.py
Reverts getsentry/self-hosted#2274
=> Revert "Move open ai key from env variables"

docker-compose.yml
picks up security fix
https://mailman.nginx.org/pipermail/nginx-announce/2024/NW6MNW34VZ6HDIHH5YFBIJYZJN7FGNAV.html
=> Bump nginx version

sentry/sentry.conf.example.py
I simplified the if request at the `sentry.conf.example.py`.
=> simplify if for open-ai-suggestion

docker-compose.yml
Release info: https://github.com/maxmind/geoipupdate/releases/tag/v6.1.0
=> deps: bump maxmind/geoipupdate to 6.1.0

sentry/sentry.conf.example.py
Remove duplicate feature flags that were added in the last release.
=> Remove duplicate feature flags

docker-compose.yml
Reverts https://github.com/getsentry/self-hosted/pull/2371 and closes https://github.com/getsentry/self-hosted/issues/2567
=> Fix defunct java processes

sentry/enhance-image.example.sh
better prevent commands silently failing
=> add `-euo pipefail` to enhance-image.example.sh

sentry/sentry.conf.example.py
Ref https://github.com/getsentry/relay/pull/3916
=> ref(feedback): cleanup topic rollout option

install/_min-requirements.sh
https://github.com/getsentry/self-hosted/pull/3275#issuecomment-2305356940
=> fix: more leeway for minimum RAM

clickhouse/config.xml
Fixes https://github.com/getsentry/snuba/issues/6305
=> fix(clickhouse): Allow nullable key

sentry/sentry.conf.example.py
ref
- https://github.com/getsentry/sentry/pull/79790
=> ref(feedback): remove issue platform flags after releasing issue types

sentry/sentry.conf.example.py
Reverts getsentry/self-hosted#3397
https://github.com/getsentry/self-hosted/pull/3397#issuecomment-2442142424
=> Revert "ref(feedback): remove issue platform flags after releasing issue types"

redis.conf
Follow up to https://github.com/getsentry/self-hosted/pull/3427#issuecomment-2485612688
=> fix(redis): Use a safer eviction rule

.github/workflows/test.yml
=> ci: Move self-contained action reference to master branch

.github/dependabot.yml
https://github.com/getsentry/security-as-code/pull/1191
=> Hand off open-source to dev-infra

.vscode/settings.json, action.yaml
Came as a feature request from @untitaker and I think it makes a lot of sense
=> feat: Require both inputs to be set on action

sentry/sentry.conf.example.py
=> feat(features): enable trace view

sentry/sentry.conf.example.py
Closes #3613 
cc @bruno-garcia @billyvg 
=> feat(features): enable session replay canvas

sentry/sentry.conf.example.py
Closes https://github.com/getsentry/self-hosted/issues/1866
=> feat(sentry): add dynamic sampling feature to config

install/dc-detect-version.sh
Fixes https://github.com/getsentry/self-hosted/issues/3630.
=> Fix STANDALONE_COMPOSE_VERSION variable setting

sentry/sentry.conf.example.py
=> ref: remove SENTRY_USE_BIG_INTS (always True)

_integration-test/test_01_basics.py
Fixes problems that appear when Python SDK 3.0 will be released.
=> Make usage of Python SDK future proof

install/set-up-and-migrate-database.sh
a hard stop is in place with this so it can be removed now
=> remove index workaround

sentry/sentry.conf.example.py
Follow up for https://github.com/getsentry/self-hosted/pull/3747
=> chore: provide detailed note for sentry endpoint settings

docker-compose.yml
=> feat: Relay healthcheck

.github/workflows/enforce-license-compliance.yml, .github/workflows/pre-commit.yml, .github/workflows/release.yml, .github/workflows/shellcheck.yml, .github/workflows/test.yml
Resolves https://github.com/getsentry/self-hosted/security/code-scanning/2
Resolves https://github.com/getsentry/self-hosted/security/code-scanning/4
Resolves https://github.com/getsentry/self-hosted/security/code-scanning/7
Resolves https://github.com/getsentry/self-hosted/security/code-scanning/14
Resolves https://github.com/getsentry/self-hosted/security/code-scanning/15
=> chore: resolve GHA code scanning alerts

.github/workflows/test.yml, _integration-test/test_01_basics.py, action.yaml
=> test: run errors-only integration tests
