- docker-compose.yml
I think this should be part of the default settings. Otherwise, taking sentry down with
```
docker-compose down
```
means we just lost all the data in postgres, including users data and events gathered so far.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/onpremise/4)
> Mount docker postgres volume on host

- README.md
This is a PR adding instructions around utilizing the contents of this repository to lift a fully working Sentry install on Docker. It fills some gaps that the current docker related docs don't cover.
This is a bit more informative than #5 and covers some of the concerns in #2
> Enhanced README with Instructions!

- Dockerfile
8.10 was released on 2016-11-01
> Upgrade to use sentry 8.10

- README.md
- docker-compose.yml
- upgrade docker compose to 3.4
- use `depends_on`
- reuse a `default`  block
- use docker named volumes
and some readme fixes
> Docker compose 3.4

- .env.example
- .gitignore
- README.md
- docker-compose.yml
This pull request improves upon #105 ( and follows for rejected #115 )
- removed from readme all references for bind mounting storage ( replaced with docker volumes in #105 )
- volumes are now declared as external, to make them more durable ( regular volumes will be deleted when you, for example, run `docker-compose down -v`)
- moved `SENTRY_SECRET_KEY` to .env file that is not part of git repo (so setup from here can be used  directly)
- added `docker-compose.override.yml` to .gitignore file ( so base setup can be extended, I, for example, used that to add a label to web container to get traefik routing for https )
> Improve setup

- README.md
Because for less hardware requirements, will give migration and create default user errors: #114, #49, #147
> Add Minimum Hardware Requirements

- sentry.conf.py
This removes auto-binding of various values (specified in config.yaml) when they're not actually configured. It ensures that these values can then be configured from the web UI as Sentry has intended.
See also https://github.com/getsentry/docker-sentry/issues/163#issuecomment-483011252
> feat: Improve configuration to be less Docker-specific

- sentry.conf.py
Exception: 'mail.enable-replies': got <type 'str'>, expected boolean
> Fix: 'mail.enable-replies' type

- .gitignore
Remove a match-all glob pattern. It looks like some non-git tools read the `*,cover` as `*` and `cover` separately and basically ignore all files. Even though this is not really a problem with the repo itself, I think the change is still valid, considering `*,cover` looks like an invalid rule anyway.
_____
Background:
(__This part is vim-specific__)
For a while now, my Neosnippet configuration has been going for a toss when working on our fork based off of this repo. I see a message similar to the one reported [here](https://github.com/Shougo/neocomplcache.vim/issues/468), but my vimrc configuration is as per the documentation available in the plugin docs. I finally spent enough time to debug this today, and it turns out this issue was happening *only* in this repo and nowhere else. So I …
> Fix possible typo in gitignore

- sentry.conf.py
Django 1.6 already defaults to `True` for this and in Django 1.8, which
is what the latest Sentry uses, the option is removed and causes a DB
connection error so dropping it to fix git builds.
See https://stackoverflow.com/a/29444039/90297.
> fix(config): Remove autocommit option from DB config

- Makefile
Required after #211. Fixes #216. Also fixes printing of `-e` after #215.
> fix(Makefile): Fix invalid reference format error

- Makefile
Dockerfile expects the argument to be `SENTRY_IMAGE`. So, modifying Makefile to enable `make build`
> Dockerfile & Makefile argument name mismatch

- sentry.conf.py
This patch introduces the following fixes to uWSGI config which
was not set up correctly to be used publicly (not behind a router,
load balancer, proxy like nginx etc.):
- Use `http` option for a front-proxy
- Set protocol back to `uwsgi` due to above
- Prevent forced socket binding to `uwsgi` due to protocol change
above (https://git.io/fj7Lw)
- Turn on "keep-alive" support
Should fix getsentry/sentry-cli#40.
> fix(uwsgi): Fix broken uWSGI config

- Dockerfile
Resolves [Warning] One or more build-args [SENTRY_IMAGE] were not consumed.
> Declare ARG in Dockerfile.

- install.sh
We need to run `snuba migrate` to be able to safely upgrade between Snuba versions
> fix(snuba): Add migrate call on setup

- docker-compose.yml
Disables the annoying automatic support metrics for Kafka and ZK while defaulting all logs to WARN level, instead of some being WARN and some ERROR.
> fix(kafka): Disable support metrics in Kafka & ZK

- docker-compose.yml
Plugs all the holes (`VOLUME` defs) in the images we use so they at least persist across runs/restarts for things like random logs or SMTP spool. This also fixes symbolicator_cleanup service not having access to symbolicator data.
> fix(volumes): Fix creation of random volumes at every run

- docker-compose.yml
- install.sh
- sentry/config.example.yml
Moves `sentry-data` volume to `/data` mount point and sets all file-based storage settings to `/data/files`, `/data/dsym-cache` etc. accordingly. See https://github.com/getsentry/sentry/blob/50ac5506669043dd939dd0e44fe4cfb00377ff1d/src/sentry/options/defaults.py#L45-L54
> fix(data): Use `/data` for persisting files and file caches

- install.sh
With this patch, `./install.sh` becomes safer as it won't recursively move things under `/data/file`. It also won't try to migrate an empty volume.
> fix(sentry-data): Don't migrate when not needed

- install.sh
Upgrades existing events from last `$SENTRY_EVENT_RETENTION_DAYS`
to Snuba automatically. Relies on ~~getsentry/sentry#15934~~.
> feat(upgrade): Add automatic Snuba migration for upgrades

- README.md
- install.sh
Fixes #278, fixes #301, fixes #302.
> fix(upgrade): Fix upgrade instructions and script

- docker-compose.yml
We were not running the post-process forwarder, causing post-process to not run which covers all plugin and rule/alert work.
Fixes #287.
> fix(post-process): Add missing post-process-forwarder

- .gitignore
- README.md
- install.sh
This change makes the install script create a new install log file, `sentry_install_log-<ISO_TIMESTAMP>.txt`, for each run and records all the output there for future reference.
> feat(install): Add automatic logs to install script

- install.sh
Since we are [moving the eventstream into a proper db migration](https://github.com/getsentry/sentry/pull/16226), we need Snuba and its friends ready at the time of `sentry upgrade` command. This patch does exactly that.
Unblocks https://github.com/getsentry/sentry/pull/16226
> fix(migration): Move Snuba bootstrapping before DB upgrade

- install.sh
This became obsolete thanks to getsentry/sentry#16226
> ref(install): Remove manual eventstream backfill

- sentry/sentry.conf.example.py
This is just a refactor. The class does the same thing, but has been renamed.
> ref(settings): Changing search class to use new class name

- install.sh
With #343, we added the `--parallel` flag which only got introduced in `docker-compose` `1.23.0` (source https://medium.com/schkn/parallelize-your-docker-compose-build-8ac653e3e596 as Docker docs themselves don't really mention these) so bumping the minimum required version.
Fixes #351.
> build(compose): Bump required compose version

- sentry/sentry.conf.example.py
- parse SENTRY_EVENT_RETENTION_DAYS as integer in case it is defined as a string like in kubernetes
> fix(config): parse env variable as int

- install.sh
Update exit -1 to exit 1 in line with best practices
Fixes premature exit of the script when checking for sse42 support. The script would exit before displaying the reason for failure to the user.
discussion started here: https://github.com/getsentry/onpremise/issues/370
I have opted for the simplest fix unless it is needed that the cleanup script runs after the version checks fail.
> fix(install): Update exit status and fix premature exit

- README.md
This addreses multiple questions raised about how to install a specific version of Sentry or using specific versions for images such as #378, #355, #348, and #326.
> docs(versioning): Add section about versioning and SENTRY_IMAGE

- install.sh
Issue: I'm deploying sentry onpremise via ansible. After I make changes to the configuration I re-run the install script to update the configuration. But every run of the install script will re-generate the secret key, and therefore trigger the (update) install handler every ansible run.
Solution: Only generate a secret key if the default key has not been changed.
> Make secret key generation idempotent

- README.md
Typo fixed: `:lastest` to `:latest`
> docs(versioning): Fix Docker image tag name

- README.md
install.sh requires a higher (not in Debian buster available version)
> Require docker compose version in README

- docker-compose.yml
- sentry/.dockerignore
- sentry/Dockerfile
This follows the best-practice of mounting the config folder as a volume and removes the need to rebuild sentry images for config changes. Partially addresses #314.
This removes the ability to directly install a python project from inside the folder. I don't think this feature was relevant or useful for this particular on-premise setup/layout anyway.
> feat(config): Mount config as a volume to Sentry

- sentry/Dockerfile
Changing the sentry/Dockerfile to remove the WORKDIR caused the RUN install requirements to use the wrong directory as context.
The change that broke this build can be found here: https://github.com/getsentry/onpremise/commit/5f7c18bd187c649048de53c75a2fac56a4c6a5da#diff-d3d372b1d4bc8f4b875c733e504d59c9L4
I was able to test this on my build locally to verify that it works. I'm not sure if there are other implications from that PR or not. 
Related to: #407
> Fix regression from #407 for requirements install

- docker-compose.yml
clickhouse logs are not persisting inside the container which is not a good practice since it can take some storage inside the container filesystem
> add volume for clickhouse logs

- docker-compose.yml
TSDB is currently broken because we've been using redissnuba backend without running the consumers.
Add outcomes consumers with an odd value for `auto-offset-reset` to attempt to recover TSDB data from outcomes.
> fix: Add snuba outcomes consumers to setup

- README.md
We don't provide great support for Sentry Server over at Discord so remove the reference to it from the README
> docs(readme): Remove link to Discord

- docker-compose.yml
Update the consumer and replacer commands. These now take a storage
instead of a dataset name as per https://github.com/getsentry/snuba/pull/875
and https://github.com/getsentry/snuba/pull/861.
> build: Update Snuba commands

- docker-compose.yml
All the other services have a restart-policy, apart from these new ones added in #421
> Use restart-policy for nginx & relay

- docker-compose.yml
- install.sh
- relay/config.yml
Fixes the issue reported on https://github.com/getsentry/onpremise/pull/421#issuecomment-619434942 and https://forum.sentry.io/t/could-not-write-etc-relay-credentials-json/9558?u=byk
Follow up to #421.
> fix(relay): Fix failed to write credentials

- docker-compose.yml
We regularly prune old Google Cloud Build images and also GCB registry is not accessible to everyone all the time (firewall settings, being in China, etc.)
Fixes #445.
> fix(relay): Use Docker Hub as relay image registry

- nginx/nginx.conf
- sentry/sentry.conf.example.py
Fixes #447.
This patch should also fix issuer regarding large uploads such as minidumps by turning off any buffering.
> fix(nginx): Fix proxy settings for Sentry

- docker-compose.yml
Suggested [on the forum](https://forum.sentry.io/t/connection-to-kafka-failed-when-installing/9162/10?u=byk) and the [upgrade docs](https://kafka.apache.org/25/documentation.html#upgrade) suggest upgrading from `5.1.x` without a rolling upgrade should be fine by just upgrading the code.
> upgrade(confluent): Upgrade cp-stack to 5.5.0

- sentry/config.example.yml
This PR simply adds a reference to the guide for setting up the Slack integration. The url was obtained from [#249](https://github.com/getsentry/onpremise/issues/249#issuecomment-547117033).
> feat(slack-integration): add reference to guide

- install.sh
Since https://github.com/getsentry/snuba/pull/943 the bootstrap command
performs a full migration. There is no longer a need to run bootstrap
followed by migrate to pick up all of the migration statements.
> feat(snuba): Skip snuba migrate task

- nginx/nginx.conf
- sentry/sentry.conf.example.py
This patch brings back the HTTP/1.1 related settings for uWSGI to fix #486 as apparently Relay tries to talk to Sentry Web with keep alives where uWSGI terminates the connection unexpectedly. It also ports some configs for uWSGI and nginx from single-tenant.
> fix(uwsgi): Make sure uWSGI talks proper HTTP/1.1

- install.sh
This also uses SENTRY_VERSION instead of hard-coding `:latest` as the tag when pulling (follow up to #509).
> fix(install): Skip pull when SENTRY_IMAGE is set

- sentry/sentry.conf.example.py
Discover v2 is now enabled by default: getsentry/sentry#19023
> ref(sentry): Remove explicit Discover v2 flags

- docker-compose.yml
This adds the missing sessions consumer for snuba to the on-prem setup.  Without this
release health data will not be consumed.
> feat: Add sessions snuba consumer to setup

- relay/config.yml
Based on my forum post https://forum.sentry.io/t/sentry-native-and-kafka-messagesizetoolarge-error/9948
In short I tried to send minidumps more than 1mb(in fact 2mb), and relay service failed to store event, with kafka error `MessageSizeTooLarge`.
You can reproduce this if you recreate install this on local machine, create simple native project, and send minidump file more than 1mb via curl like suggested in docs or in web ui. And check the logs.
I reason selected value of 50mb on https://github.com/getsentry/onpremise/blob/master/docker-compose.yml#L87, like you already hardcoded on kafka service.
> fix(relay): Increase Kafka message size limit to 50MB

- install.sh
Hi,
I've been through quite a few different ways of implementing this fix and settled on creating a variable to store the output of checking whether the zookeeper copy target folder exists and copying the snapshot file based on the copy target folder existing. I've ran quite a few manual tests for each option as well. Currently the PR sits on Option 3 from the below options.
**Option 1**
Judging from the [Jira issue](https://issues.apache.org/jira/browse/ZOOKEEPER-3056), it seems like the work around for zookeeper upgrades could be omitted entirely since the issue relates to upgrades from v3.4.10 to v3.5.4. I've tested removing the zookeeper workaround entirely and that install ran smoothly on a clean install of Sentry (no existing data) as well as an install of Sentry that currently has …
> fix(zookeeper): cp: cannot create regular file

- sentry/config.example.yml
This is all i needed to get the plugin working after the latest changes in https://github.com/getsentry/sentry/pull/19446 
due to the default being true it meant certain endpoints just borked on the newer api
> fix(slack): Add note about legacy app flag for newly created bots

- .gitignore
- install.sh
- relay/config.example.yml
- sentry/sentry.conf.example.py
This patch adds `INTERNAL_IPS` definition to `sentry.conf.py` by sniffing the network from eth0 and relies on this for trusted Relays instead of the ALLOWLISTED PKs. This removes the necessity of syncing Relay PKs to `sentry.conf.py`.
This PR needs getsentry/sentry#19798 to work.
> ref(relay): Remove PK and rely on INTERNAL_IPS

- sentry/sentry.conf.example.py
Fix #486.
I finally figured out what the issue was: a missing `post-buffering` option to let Relay finish it's POST request for auth. This PR supersedes #543.
> fix(relay): Fix relay cannot authenticate w/ Sentry

- .travis.yml
- install.sh
- sentry/sentry.conf.example.py
- test.sh
This is a long-needed test that tests the whole pipeline from Nginx, Relay, to Kafka, and Snuba. The final missing piece is testing the Symbolicator integration.
This PR is also a follow up to #576 as it didn't solve the Relay issues fully (the earlier fix was a coincidence or is not as reliable as it seemed).
Fixes #486 (finally?).
> fix(ingest): Fix Relay auth issues and add e2e event ingestion test

- sentry/sentry.conf.example.py
`INTERNAL_IPS` is used to check whether to allow superuser access or not. Limiting this to the Docker internal network makes it impossible for anyone to reach admin pages with on-premise setup.
This is a follow up to #572 and it fixes #577.
> fix(superuser): Don't set INTERNAL_IPS to Docker network

- sentry/sentry.conf.example.py
The discover-basic and discover-query feature flags are enabled by default in the built-in sentry/conf/server.py
Closes #582
> feat: Enable performance views for on-premise

- docker-compose.yml
Without the consumer-group option, transactions consumer and events consumer will compete for messages on the same topic and usually events win, which is the first one. This may cause some data loss for performance and make it seem not work.
Should address https://forum.sentry.io/t/perfomance-tracing-for-sentry-itself/10405/5?u=byk
> fix(snuba): Add consumer group to transactions consumer

- .env
- docker-compose.yml
- scripts/bump-version.sh
- sentry/Dockerfile
This change allows one to override any Sentry service image, mostly for testing purposes. It also removes the SENTRY_VERSION variable as docker-compose makes it very hard to cascade default values for these. Next step is to have integration tests in getsentry/snuba and getsentry/relay (and possibly for getsentry/symbolicator) for getsentry/onpremise using this PR.
Also related: #596.
> feat(compose): Add ability to use custom images for any Sentry service

- docker-compose.yml
- install.sh
> fix(install): Read and set .env in install.sh

- sentry/sentry.conf.example.py
Fixes a small typo in a example configuration comment
> typo: Example configuration comment

- .github/workflows/test.yml
This is a fairly wooden port of the Travis CI config to GitHub actions. Note that this doesn't remove Travis yet. I figure we should run both in parallel for a bit to make sure GitHub Actions is trustworthy. E.g., there might be some caching we want to do to speed up the build, I didn't look into that yet.
Presumably there's some button clicking that needs to happen before this'll run in the main repo. Here's a good run in my fork:
https://github.com/chadwhitacre/onpremise/runs/998127947
And here's a sample bad run in my fork, showing that test failures indeed break the build:
https://github.com/chadwhitacre/onpremise/runs/998137076
Part of #627.
> ci(github): Reimplement CI in GitHub Actions

- nginx/nginx.conf
If we are going to define a custom log format, we should probably be using that format.
Fixes #635
> Use the custom Nginx access log format

- .github/workflows/test.yml
- .travis.yml
- install.sh
This continues on the ideas from #607. By "downtime" here I mean "not accepting events" - web, smtp and background processes are out of scope.
This PR adds a `--minimize-downtime` option to install.sh. This options changes the behaviour of the script by:
1. keeping nginx and relay running until the very end,
2. disabling cleanup on exit and failure,
3. explicitly reloading nginx configuration,
4. and starting the whole cluster at the end.
This is a work in progress, and only tested on a local, non-production instance. But the results are promising: no downtime if relay version doesn't change, and only a second when it does. So far this was only tested with a curl loop, so I'm still not sure if Relay flushes the events to Sentry before getting recreated by `$dc up`.
> install: Keep relay available while upgrading

- .github/workflows/test.yml
- test.sh
This also brings in common pre-test commands into test.sh file.
> ci: Disable beacon on CI e2e tests

- README.md
Fixes an issue where we recommend adding TLS terminating Nginx into the docker-compose file. This is no longer recommended as we already have an nginx instance there for routing purposes.
Fixes #653.
> fix[readme): Don't recommend nginx in docker-compose

- install.sh
The code assumed GNU getopt, which is not the default on many platforms, notably OSX.
Fixes #656, and replaces #659.
> fix(install): Don't use getopt for options parsing

- clickhouse/config.xml
- docker-compose.yml
Closes #616, supercedes #651
Adds an option to reduce max memory usage of Clickhouse server. Sets it to 30% of all available RAM as the default.
Co-authored-by: @renchap
> feat(clickhouse): Reduce max memory usage to 30% of RAM

- .github/workflows/test.yml
GitHub team pointed us to docker/compose#3586 as the likely root cause and some digging around got us to https://git.io/JUn7p as a potential fix, which we are trying here.
> ci(gha): Fix intermittent test failures

- docker-compose.yml
Fixes #502 and applies the suggestions from there:
- Number of partitons=1 (from 40)
- Log retention to 1 day (from 7 days)
These settings should be more suited towards the scale this repo is intended for.
NOTE: The partition count change will only affect new installs unless `sentry-kafka` and related volumes are cleaned.
> fix(kafka): Reduce Kafka resource usage

- install.sh
Fixes https://github.com/getsentry/onpremise/issues/672
I split this PR up into 4 commits. The first one is the bare minimum for the issue. The rest are just consistency corrections that we neckbeards at irc://chat.freenode.net/%23bash would always make.
> fix(install): Use proper bash testing

- .github/workflows/test.yml
- README.md
- install.sh
We need `docker-compose ps -a` for CI so we were already using 1.24.1, this aligns the rest with that.
For Docker, there are a bunch of network-related fixes in 19.03.12 and prior (DNS fallback and IPv6 advertising) that we'd like to have to see if they are going to fix some reported connectivity issues w/ onpremise.
> build(docker): Bump min Docker & Compose versions

- docker-compose.yml
@xbenjii reported the following error on #629:
>You requested maxclients of 10000 requiring at least 10032 max file descriptors.
Increasing this limit by default makes sense to make Redis more available to heaveier loads.
> fix(redis): Increase file descriptors to 10032

- README.md
Our relay connection wasn't behaving correctly because of some missing config in our `sentry.conf.py`. Also, we didn't have the performance module enabled because of a missing feature flag.
That's why an entry in the documentation regarding this would be nice.
> State that config files need to be updated as well

- test.sh
We were relying on the public DSN field coming first from the API and with Python 3, that's not the case to the tests were failing. This PR makes DSN extraction a bit more robust while still avoiding a full-fledged JSON parser.
Unblocks getsentry/sentry#21126
> fix(py3): Make event ingestion test more robust

- README.md
- Change minimal Docker version to the one in `install.sh`
- Add an extra link to the documentation
- Change the existing link to point to the correct one.
> docs: Update README with several improvements

- install.sh
This is to ensure clean shutdown of Celery, with fully drained queues. This is needed as versions may change the event format and not be backwards compatible. FWIW this is a hacky workaround without a strong guarantee that the queues will be empty. Ideally we'd shutdown everything first, spin up the workers and check for queues being drained every second or so.
> fix(install): Increase stop timeout to 60 seconds

- docker-compose.yml
I only tested error alerts while testing, turns out this was broken in both dev and on-prem. This
fixes the issue.
> fix(metric_alerts): Fix transaction alerts

- install.sh
We kept getting issue reports that we traced down to `git-bash` which doesn't seem to play nice with Docker for Windows with bind mounts. This PR uses the existence of `$MSYSTEM` to detect `git-bash` and exit early with a relevant message.
> fix(install): Disable the script on git-bash

- .github/workflows/release.yml
Adds names to steps, adds the sleep between prep and publish, adds the global git user config..
> ci(release): Align release workflow with getsentry/sentry

- docker-compose.yml
We are already referencing this env var here:
https://github.com/getsentry/onpremise/blob/19f4561a9e2abe32dc5eb5a03a332b50f2265b4b/sentry/sentry.conf.example.py#L62-L64
@lynnagara should we be passing this to Snuba and any other services too?
> fix(sentry): Pass SENTRY_EVENT_RETENTION_DAYS to sentry services

- docker-compose.yml
Follow up on #754. Depends on getsentry/snuba#1526.
> fix(snuba): Pass SENTRY_EVENT_RETENTION_DAYS to Snuba instances too

- clickhouse/config.xml
I've noticed clickhouse complaining about this missing setting, which stopped clickhouse from starting up with version 20.3.9.70
/cc @BYK 
Related to https://github.com/getsentry/onpremise/issues/726
> fix(clickhouse): set enable_mixed_granularity_parts to enabled

- .github/workflows/release.yml
Switches to using getsentry/action-prepare-release for common steps and removes the dry run option from the prepare stage as it prevents us from testing the publish step. Prepare step should be safe anyways and can be skipped with the `skip-prepare` input.
Related: https://app.asana.com/0/1198192131329257/1198192131329301, https://app.asana.com/0/1198192131329257/1198192573081717
> ci(release): Use action-prepare-release and rework dry-run

- .github/workflows/lock.yml
Closes https://app.asana.com/0/1199602781063150/1198192573081731.
Action does [appear](https://github.com/dessant/lock-threads/blob/63786a6c74ee3cfc4584f36de4360305c55e5126/src/index.js#L111-L119) to limit to 50 issues per run as [documented](https://github.com/dessant/lock-threads#why-are-only-some-issues-and-pull-requests-processed). We have ~800 closed issues in this repo, so that's ~16 clock ticks, rec is to start w/ hourly, then drop to daily (via additional yml commit) once initial backlog is processed.
[Action](https://github.com/dessant/lock-threads) has 150 stars (not a _lot_ but not a little for something like this) and the [author](https://github.com/dessant) seems legit. I gave the code a skim and did not see anything obviously malicious. MIT.
> Lock closed issues/PRs via 3rd-party action

- .github/workflows/lock.yml
> Tighten up name and schedule

- .craft.yml
- .github/workflows/release.yml
- scripts/bump-version.sh
- scripts/post-release.sh
A copy of getsentry/sentry#22657 with fixes included.
That said this one is a bit different. We used to use the extra option `no-merge` when publishing to keep the release branches and also keep master on nightly versions. If we want to keep this, we need to add per-project overrides to getsentry/publish which would increase complexity at this early stage for this fringe case. Instead, I opted to follow what getsentry/sentry does: merge but then immediately after that update the version.
> ci(release): Move to getsentry/publish for releases

- .github/workflows/lock.yml
[Failing](https://github.com/getsentry/onpremise/runs/1571980788?check_suite_focus=true#step:1:14) with:
> Download action repository 'dessant/lock-threads@63786a6c74ee3cfc4584f36de4360305c55e5127'
Error: An action could not be found at the URI 'https://api.github.com/repos/dessant/lock-threads/tarball/63786a6c74ee3cfc4584f36de4360305c55e5127'
Will this convince actions to parse as SHA?
> Futz with action pin syntax

- .github/workflows/stale.yml
https://app.asana.com/0/1199602781063150/1198192573081727
- Labels un-triaged issues with `Status: Stale` after three weeks of inactivity.
- Closes issues so labeled after one more week of inactivity.
- Use `Status: Accepted` to hold open indefinitely.
> meta: Install stalebot

- .github/workflows/release.yml
We need this for automated version numbers
> ci(release): Enable the CalVer flag for release

- install.sh
In #787 we decided to up the minimum RAM requirement from 2.4 to 8 GB, handled the README in 2dadbda1cc44e5a9a1c1a84f6dd0306258f17a47, now for `install.sh` ... where it really matters. :)
h/t @AlexanderRydberg
> Bump RAM requirement in install.sh

- install.sh
- install/docker-aliases.sh
- install/geoip.sh
This works better in, e.g., GCE.
DRY up dc/dcr aliases in the process.
> Source install/geoip.sh, to work in more envs

- relay/config.example.yml
As mentioned on the forum, this is stable enough and solves a big, ongoing issue with relay unable to connect to any internal services: https://forum.sentry.io/t/relay-errors-in-fresh-new-on-premise-install/9804/24
Should fix #771.
> fix: Enable experimental reqwest library for relay

- .github/workflows/test.yml
- install.sh
- install/geoip.sh
- install/py2-warning.sh
Removes the obsolete `echo ''` at the end, tries to make sure we see the warning on CI too.
> fix: Fix Py2 warning

- .github/workflows/test.yml
Based on my reading, this error comes from urllib3.
https://urllib3.readthedocs.io/en/latest/advanced-usage.html
>The behavior of the pooling for ConnectionPool is different from PoolManager. By default, if a new request is made and there is no free connection in the pool then a new connection will be created. However, this connection will not be saved if more than maxsize connections exist. This means that maxsize does not determine the maximum number of connections that can be open to a particular host, just the maximum number of connections to keep in the pool.
I think the ideal solution would be to add `retry` and `block` options to [docker-py](https://github.com/docker/docker-py/blob/ce2669e3edfe5d3215ba501cc9771fc0ffad680a/docker/transport/unixconn.py#L58-L70) but that's a long …
> ci: Increase pool size to prevent pool closed errors

- .github/workflows/validate-new-issue.yml
https://github.com/getsentry/.github/issues/8
- Use envvar for authentication (better place for secrets).
- Skip validation for staff (less noise when we go to `sentry`).
- Link to "closing" comment at the end.
> Improve on issue validation

- scripts/post-release.sh
Fixes the issue we had over at getsentry/publish#60. This aligns the script with [the one at getsentry/sentry](https://github.com/getsentry/sentry/blob/master/scripts/post-release.sh#L6)
> ci(release): Make sure to pull before pushing in post-release

- .github/workflows/test.yml
- install.sh
Fixes #823. In `install.sh` we build a local sentry image that is used by many services from using the build context under the `./sentry` directory. To avoid building this image multiple times, we also give it a specific name which is referred from multiple services. The issue is, we also run `docker-compose build --parallel` which creates a race condition when building this image as `docker-compose` doesn't check whether the image is already there or not. This is the root cause of all these random failures: an unsurprising race condition.
> ci(test): Fix 'pool is closed' errors

- nginx/nginx.conf
Removes the obsolete and confusing `X-Real-IP` header setting from the Nginx config.
> fix(nginx): Remove X-Real-IP header entry

- README.md
When trying to install self-hosted Sentry on Google Cloud Compute container-optimized OS, I hit an issue where the disk space was not sufficient to even build local images. Given Kafka and Clickhouse are also quite disk-intensive, it makes sense to add this to the docs.
Opted not to add an automated check for this as it is not easy to determine the path Sentry installation will consume, hence the free space there.
> docs: Add 20 GB minimum disk space requirement

- .github/workflows/validate-new-issue.yml
Copied/pasted from https://github.com/getsentry/.github/commit/61a392d38bfa7bd4a8b9b4cafd28b2ad5cb8bb37.
I believe this breaks on templates that have no headings, but we don't have any of those in this repo.
> Deploy latest validate-new-issue.yml

- install.sh
On machines with 4gb the available memory is often a little bit lower than 4000
closes #839
> Change MIN_RAM_HARD from 4000 to 3800

- sentry/config.example.yml
Fixes the issue where we set an invalid option, `github-app.extended-permissions`, instead of the correct one, `github-login.extended-permissions`. Some people mentioned this warning earlier but never clearly enough to point that it was coming from our default settings suggestions.
> fix(config): extended-permissions is on github-login, not app

- README.md
- install.sh
Adds minimum of 4 CPU cores requirement as anything below will perform quite poorly even on lower loads. Relaxes the soft RAM requirement from 8000 MB to 7800 MB as even when there is 8 GB RAM installed, the system reserves some of it to itself and under reports the amount.
> ref(requirements): Add min CPU requirement, relax soft RAM

- .github/workflows/validate-new-issue.yml
I are a bot. 🤖
https://github.com/getsentry/.github/blob/7ef208419a2a6e5c1cb569c73e3b3d96dd2ddf9a/.github/workflows/validate-new-issue.yml
> meta(gha): Deploy action validate-new-issue.yml

- install.sh
Hi!
This PR fixes a typo in `install.sh` - there should be no `MB` in the context of CPU cores number
> fix: Typo in the "recommended minimum CPU cores" message

- docker-compose.yml
- test.sh
Fixes #860 and adds a test case to ensure all cleanup jobs are working.
> fix(cron): Fix sentry-cleanup entrypoint issue

- docker-compose.yml
These were looked over when they were added. This is not a big deal as running `docker-compose up -d` spins up all services but this fix is for correctness sake, especially for folks using this repo as a basis for more complex setups.
> fix(deps): Add missing snuba consumer dependencies to Sentry

- relay/config.example.yml
As per https://github.com/getsentry/relay/pull/938 this option no longer
exists. Existing values will be ignored, however.
> fix(relay): Remove http._client usage

- scripts/post-release.sh
We've been leaving onpremise master with the latest release, instead of nightly builds for 2 releases now. Even if the post-release script runs, it bumped the versions to nightly on the release branch, making it effectively a no-op. This should be addressed in Craft via getsentry/craft#115 but until then, we need this extra line.
> fix(release): Fix post-release script so it operates on master

- .github/workflows/stale.yml
This PR adds the 2 new triage labels to replace old ones:
1. `Status: Accepted` -> `Status: In Progress`
2. `Status: On Hold` -> `Status: Backlog`
> ci(stalebot): Add new triage labels

- .github/workflows/stale.yml
This PR removes the 2 old triage labels replaced with new ones:
1. `Status: Accepted` -> `Status: In Progress`
2. `Status: On Hold` -> `Status: Backlog`
> ci(stalebot): Remove old triage labels

- install.sh
- install/_lib.sh
- install/_test_setup.sh
- install/create-docker-volumes-test.sh
- install/create-docker-volumes.sh
- install/geoip-test.sh
- install/geoip.sh
- install/migrate-file-storage.sh
- install/relay-credentials-test.sh
- install/relay-credentials.sh
- install/restart-carefully.sh
- install/set-up-and-migrate-database.sh
- install/upgrade-postgres.sh
- Use source appropriately (needed for config to propagate properly)
- Standardize group/endgroup line-spacing
- Clean up envvar defaults
Part of #795.
> Clean up the refactor

- install.sh
- install/_lib.sh
- install/bootstrap-snuba.sh
- install/build-docker-images.sh
- install/create-kafka-topics.sh
- install/ensure-files-from-examples.sh
- install/generate-secret-key.sh
- install/replace-tsdb.sh
- install/set-up-zookeeper.sh
- install/turn-things-off.sh
- install/update-docker-images.sh
This refactors without adding unit tests, to meet a minimum bar to close #795. Now that we have a testing pattern/framework in place we can add tests opportunistically in the future as we work on different components.
> Refactor most of the rest of install.sh

- docker-compose.yml
This change ensures that the Snuba consumer and replacer start
to fill in the new table. It should be applied once we have
backfilled data and are ready to cut over to the new storage.
It should be part of the 21.4.0 release.
Depends on https://github.com/getsentry/snuba/pull/1801
> feat: Update storage target for Snuba consumer and replacer.

- README.md
Explains how to set the version on Linux where `sudo` is required. Based on this Stack overflow answer: https://stackoverflow.com/questions/8633461/how-to-keep-environment-variables-when-using-sudo/8636711#8636711
> docs: explain changing version on Linux

- relay/config.example.yml
This comment has unprofessional tone and does not serve any purpose. Since this is copied to every onpremise installation and I keep copying this code to public issue comments, it's better removed.
> ref(relay): Remove comment from sample config

- docker-compose.yml
This is a stop-gap solution to #918 until we figure out the negative DNS caching issue inside `relay`. This may also be due to Docker Compose making some assumptions/optimizations/limiting regarding cross-container access unless they are explicitly linked via the `depends_on` key.
> fix: Make relay depend on web for DNS resolution

- .github/workflows/issue-status-helper.yml
I are a bot, here to deploy [issue-status-helper.yml](https://github.com/getsentry/.github/blob/c47baae9fa40046424bda5ff741a8216b2f6f623/.github/workflows/issue-status-helper.yml). 🤖
> meta(gha): Deploy action issue-status-helper.yml

- .github/workflows/issue-routing-helper.yml
I are a bot, here to deploy [issue-routing-helper.yml](https://github.com/getsentry/.github/blob/c3d0c77c6dfb3998a37ba62476f51281f424f132/.github/workflows/issue-routing-helper.yml). 🤖
> meta(gha): Deploy action issue-routing-helper.yml

- docker-compose.yml
Add basic healthchecks on Zookeeper & Kafka containers to have a view on container status. These checks are quite basic because I have no knowledge at all on these components.
> feat: Add basic healthchecks for Zookeeper & Kafka

- .env
- .gitignore
- docker-compose.yml
- install.sh
- install/install-wal2json.sh
- postgres/init_hba.sh
- postgres/postgres-entrypoint.sh
- scripts/bump-version.sh
This is an RFC on how to set up Change Data Capture.
We will use Change Data Capture to stream WAL updates from postgres into clickhouse so that features like issue search will be able to join event data and metadata (from postgres) through Snuba.
This requires the followings:
- A logical replicaiton plugin to be installed in postgres (https://github.com/getsentry/wal2json)
- A service to run that streams from the replication log to Kafka (https://github.com/getsentry/cdc)
- Datasets in Snuba.
This PR is preparing postgres to stream updates via the replication log.
The idea is to 
- download the the replication log plugin binary during install.sh
- mount a volume with the binary when starting postgres
- providing a new entrypoint to postgres that ensures everything is correctly …
> feat(cdc): Prepare the self hosted environment for the Change Data Capture pipeline

- .gitattributes
Follow-up to #973. Restores exporting test.sh so that integration tests can use
it after downloading the release archive.
> fix(test): Export test script

- docker-compose.yml
> feat: Add healthchecks for redis, memcached and postgres

- reset.sh
The purpose of this script is to make it easy to reset a local onpremise install to a clean state, optionally installing a particular version/sha. This is helpful for testing out upgrade scenarios such as in https://github.com/getsentry/sentry/issues/26134.
> Make a reset button

- README.md
Closes #983 and closes #790.
Refs getsentry/develop#355.
> docs: Fold README into self-hosted docs

- docker-compose.yml
- install/wrap-up.sh
This PR is a try to update most middlewares used by Sentry to latest stable versions.
[As mentioned in the forum](https://forum.sentry.io/t/middleware-version-compatibility/14353/2) I didn't update Postgresql & Clickhouse due to known issues.
I also :
- changed versions to immutable tags (MAJOR.MINOR.PATCH semver versions when possible).
- changed nginx to the Alpine variant
> Update middlewares to latest stable versions

- docker-compose.yml
The 2s interval caused constantly high CPU usage. 30s interval with 3 retries is the Docker default and doesn't hurt the system that much.
Fixes #1000
> fix: raise healthcheck interval for redis, memcached and postgres

- CHANGELOG.md
This adds a breaking change notice to our changelog regarding custom plugins:
The frontend bundle will be loaded asynchronously. This is a breaking change that can affect custom plugins that access certain globals in the django template. Please see https://forum.sentry.io/t/breaking-frontend-changes-for-custom-plugins/14184 for more information
> docs(): Add notice about breaking change for custom plugins

- .github/ISSUE_TEMPLATE/bug.yml
Follow-up to b30e7ef94b3e5a4cbe04ff5c9c3d92aff75f93f7. This is not required in `sentry` because most folks are on SaaS and we don't care about version for that.
> Require version on bug form

- docker-compose.yml
Fixes #1009 by partially reverting #1002. We need to make a 21.6.2 release soon and I didn't have time to dig into why Kafka upgrades were failing so reverting for safety for now.
> fix(kafka): Get Confluent images back to 5.5.0

- install/install-wal2json.sh
There is a potential conrner case where we may end up with the wal2json library in the `postgres/wal2json/VERSION/file` but not in `postgres/wal2json/wal2json.so`.
Not sure exactly how likely this could be, but thechnically it is possible that the download succeeds and `cp "../postgres/wal2json/$VERSION/$FILE_NAME" "$FILE_TO_USE"` does not. The next attempt the copy would not be attempted.
This fix ensures the copy always happens
> fix(install) Make wal2json copy more robust

- install/install-wal2json.sh
`http_proxy`, `https_proxy` and `no_proxy` environment variables should be forwarded to the curl container.
> fix(wal2json): Respect http_proxy/https_proxy/no_proxy when installing

- sentry/config.example.yml
Cannot send emails after upgraded. After checking, I found that `mail.use-ssl` and `mail.list-namespace` must be set.
Add those to `config.example.yml`, make it easy to known.
> Add mail.use-ssl and mail.list-namespace in config.example.yml

- CHANGELOG.md
- install/install-wal2json.sh
Turns out the latest, `7.78.0` may have issues with DNS resolution from time to time (I experienced this locally). It is also a good practice to fix it to a specific version.
> fix: Fix `curl` image to version 7.77.0

- README.md
- install/_lib.sh
- install/check-minimum-requirements.sh
Starting from `docker-compose` v1.28.0, the `--no-ansi` option is deprecated and a new, `--ansi never` option is introduced instead. This PR makes the deprecation warnings around this go away but bumps the minimum docker-compose version required to `1.28.0` as the older versions don't support the new option.
> upgrade: use --ansi never for docker-compose

- _integration-test/run.sh
See https://github.com/getsentry/sentry/pull/27555#issuecomment-893000179.
I also thought it would be more reliable to look for it in curl's cookiejar file, but it doesn't seem to be set.
> fix(tests): Django 2.0 and 2.1 compatible csrf token extraction

- docker-compose.yml
to avoid a race condition in install.sh process at step
https://github.com/getsentry/onpremise/blob/7e7401a668987c44863c403548ba3dbf91c701da/install/bootstrap-snuba.sh#L4
closes #1033
> fix(snuba-api): wait for clickhouse to be healthy

- CHANGELOG.md
- docker-compose.yml
Expands the work on #1053 to all applicable services.
> feat: Leverage health checks for depends_on

- install/check-minimum-requirements.sh
> fix(requirements): Make compose version check bw-compatible

- CHANGELOG.md
- docker-compose.yml
> fix(clickhouse): Use correct HTTP port for healthcheck

- docker-compose.yml
We've switched to using the [compose spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md) with the recent upgrades and health-check related upgrades anyway so drop the incorrect and confusing compose file version.
> fix(compose): Drop version from compose file

- README.md
Describe an easier way to pass the `SENTRY_IMAGE` environment variable to `install.sh` when using `sudo` that doesn't require modifying the `sudo` configuration.
Simple test script:
```text
jnm@world$ cat > install.sh
#!/usr/bin/env bash
echo "It looks like you are $(whoami) and want to install $SENTRY_IMAGE"
jnm@world$ chmod +x install.sh
```
Basic environment variable test:
```text
jnm@world$ SENTRY_IMAGE=whee ./install.sh
It looks like you are jnm and want to install whee
```
Oops, `sudo` doesn't forward the variable from its own environment by default (#922):
```text
jnm@world$ SENTRY_IMAGE=whee sudo ./install.sh
[sudo] password for jnm:
It looks like you are root and want to install
```
However, there's an easier way than modifying the `sudo` configuration:
```text
jnm@world$ sudo …
```
> docs: simplify Linux `sudo` instructions in README

- reset.sh
We need $0 to evaluate as install.sh in order for check-requirements to work.
> Fix #1079 - bug in reset.sh

- .gitignore
- README.md
- install/_lib.sh
- install/wrap-up.sh
This merge request will...
- add support for a customizable `.env` file
- add `.env.custom` to `.gitignore`, so that Git will ignore changes regarding this file
- add a note regarding the customizable `.env.custom` file to the readme
Motivation:
The `.env`file provides environment specific configurations, which can be always different at each installation. Docker uses by default the `.env` file. Using the parameter `--env-file` [1], you can define a custom file.
Usually, you want to have your installation clean, so Git should not report any unstaged / uncommitted changes, when you change environment specific settings and run `git status`.
Since the `.env` file is currenlty in Git, we need a custom file, which is not in Git.
Refs:
- [1] …
> Add support for custom DotEnv file

- _integration-test/run.sh
Confusing between test cleanup and self-hosted cleanup.
> Unfrobulate "cleanup" in integration test

- .github/ISSUE_TEMPLATE/problem-report.yml
- install/_lib.sh
- install/check-minimum-requirements.sh
- install/error-handling.sh
- install/parse-cli.sh
- install/set-up-and-migrate-database.sh
- install/update-docker-images.sh
- reset.sh
The big thing here is a fix for #1132. I did a grep for `docker-compose` and cleaned up the rest of the instances. The one question I had is in CI tests ... as I read it we still need `docker-compose` there so we can test v1, which we do still want to support for now.
> Do more migrating to Docker Compose v2

- .env
- .github/ISSUE_TEMPLATE/feature-request.yml
- README.md
- docker-compose.yml
- install/_test_setup.sh
- install/replace-tsdb.sh
- install/turn-things-off.sh
- install/update-docker-images.sh
- reset.sh
https://github.com/getsentry/self-hosted/issues/796
> Rename onpremise to self-hosted

- install.sh
- install/check-latest-commit.sh
- install/parse-cli.sh
Fixes https://github.com/getsentry/self-hosted/issues/925
However this would prevent from running in isolated (without Internet) environments.
Credit: https://stackoverflow.com/a/25109122/3835210
> Check for latest commit before install.sh

- README.md
- install/check-latest-commit.sh
- install/parse-cli.sh
Quick follow-up to #1186, primarily to add the grouping we have in the other subscripts, and to give feedback when skipped.
> Docs and output tinkering for commit check

- README.md
This is a dummy PR to work around limitations with the automated changelog system we are using. Please see https://github.com/getsentry/self-hosted/issues/1196 for discussion.
> Self-hosted Sentry is not vulnerable to log4shell

- nginx/nginx.conf
https://nginx.org/en/docs/ngx_core_module.html#worker_processes:
>  Defines the number of worker processes.
> The optimal value depends on many factors including (but not limited to) the number of CPU cores, the number of hard disk drives that store data, and load pattern. When one is in doubt, setting it to the number of available CPU cores would be a good start (the value “auto” will try to autodetect it).
> Set worker process to auto

- _integration-test/run.sh
- install.sh
- install/_lib.sh
- install/dc-detect-version.sh
- reset.sh
This extends and fixes #1209 so it can be merged.
> Fix reset.sh docker-compose call

- docker-compose.yml
```
Changes with nginx 1.21.5                                        28 Dec 2021
*) Change: now nginx is built with the PCRE2 library by default.
*) Change: now nginx always uses sendfile(SF_NODISKIO) on FreeBSD.
*) Feature: support for sendfile(SF_NOCACHE) on FreeBSD.
*) Feature: the $ssl_curve variable.
*) Bugfix: connections might hang when using HTTP/2 without SSL with the
"sendfile" and "aio" directives.
```
> Bump nginx:1.21.5-alpine

- postgres/postgres-entrypoint.sh
Link /docker-entrypoint.sh is depraceted in newer postgres versions
https://github.com/docker-library/postgres/blob/3bb48045b4dc5df24bf2271c679f7a4e9efcbe6e/9.6/stretch/Dockerfile
> Deprecated /docker-entrypoint.sh call

- install.sh
Setup default [`umask`](https://en.wikipedia.org/wiki/Umask), otherwise files created with permissions that containers later can't read.
```
!! Configuration error: ConfigurationError("PermissionError: [Errno 13]
Unable to load configuration file (Permission denied):
'/etc/sentry/sentry.conf.py'",)
```
To reproduce, try:
```
git checkout 21.6.3 
umask 0007
./install.sh
```
```
root@docker2 sentry/21.6.3# ls -l sentry/sentry.conf.py
-rw-rw---- 1 root root 7.4K Dec 25 03:18 sentry/sentry.conf.py
```
also known to be broken with `21.5.0` and `9.1.2`, i.e the versions noted in hard stops:
- https://develop.sentry.dev/self-hosted/releases/#hard-stops
so, perhaps carry the fix to those branches as well
> Install: setup umask

- docker-compose.yml
- install.sh
- install/_lib.sh
- install/dc-detect-version.sh
> Take some actions to avoid unhealthy containers

- .github/workflows/test.yml
- install/create-kafka-topics.sh
- install/relay-credentials.sh
~~If it's causing issues (https://github.com/getsentry/self-hosted/issues/1133#issuecomment-1006120915) why should we stick to it?~~
~~Also while we're here let's bump docker-compose 1.x version to latest release.~~
So this PR got changed in the way and at last min/max 1.x and 2.x versions of docker-compose added to CI as suggested by @chadwhitacre in https://github.com/getsentry/self-hosted/pull/1251#discussion_r787960586
Also because of recent changes in 2.2.3 (https://github.com/docker/compose/pull/9035) `-T` had to be added to some scripts using `$dcr` where output of it was getting used.
```
-T, --no-TTY                Disable pseudo-noTty allocation. By default docker compose run allocates a TTY
```
> Add CI compose version 1.29.2 / 2.2.3

- install.sh
- install/ensure-relay-credentials-test.sh
- install/ensure-relay-credentials.sh
This is a follow-up to #1273, and it should get CI back on track on `master`.
> Clean up relay credentials generation

- install/check-minimum-requirements.sh
- install/ensure-relay-credentials.sh
> Improve logging of docker versions and relay creds

- cloudbuild.yaml
> Add a cloudbuild.yaml for GCB

- .github/workflows/test.yml
- _integration-test/run.sh
> ci: Temporary fix for interactive prompt on createuser

- docker-compose.yml
The hostname is literally set to `''`:
Before:
```
''
```
After:
```
c531c19841de
```
> Docker-Compose: Avoid setting hostname to ''

- .github/workflows/test.yml
- _integration-test/run.sh
I think this helps us running to catch any errors sooner than a PR comes up as this repository is not having so many changes and there may be many days without a CI running, and who doesn't like more testing? :)
We may want to change the time though.
> Run CI every night

- .github/workflows/enforce-license-compliance.yml
> Use a custom action

- .github/workflows/enforce-license-compliance.yml
Explanation:
https://github.com/getsentry/action-enforce-license-compliance/blob/236d528c324632485f9e8adb02b515ce01e81d12/action.yml#L16-L26
> Use better API key when available

- README.md
- cron/entrypoint.sh
- install/check-minimum-requirements.sh
- sentry/sentry.conf.example.py
see: https://github.blog/changelog/2022-04-25-git-io-deprecation/
Committed via https://github.com/asottile/all-repos
> fix: replace git.io links with redirect targets

- sentry/config.example.yml
To prevent recurrences of https://github.com/getsentry/sentry/issues/34387
> Document From email display name

- cron/Dockerfile
I'm looking to replace `gosu` with a `USER` instruction in https://github.com/getsentry/snuba/pull/2696 -- this requires us to reset the user back to root before proceeding with `apt` installation
> ref: reset user to root for installation

- docker-compose.yml
We have rebuilt the Snuba subscriptions infrastructure to help with scaling
subscriptions in SaaS. Hopefully it will be a bit more stable for self hosted
as well. It's configured to be able to recover more quickly from any downtimes or
backlogs as it ignores stale subscriptions and only executes and delivers alerts
on recent ones.
The ability to run the old subscriptions process will be removed in an upcoming
Snuba release.
> snuba: New subscriptions infrastucture rollout

- docker-compose.yml
Use volume for writable data, as it's supposedly faster because no need to update overlayfs layers on volumes.
NOTE: `nginx` itself does `chown nginx` on startup according to my tests:
```
total 0
drwxr-xr-x    1 root     root            98 Jun 12 17:05 .
drwxr-xr-x    1 root     root            19 Nov 13  2021 ..
drwxr-xr-x    2 nginx    root             6 Jun 12 17:05 client_temp
drwx------    2 nginx    root             6 Jun 12 17:05 fastcgi_temp
drwx------    2 nginx    root             6 Jun 12 17:05 proxy_temp
drwx------    2 nginx    root             6 Jun 12 17:05 scgi_temp
drwx------    2 nginx    root             6 Jun 12 17:05 uwsgi_temp
```
Refs:
- https://github.com/getsentry/self-hosted/issues/1381#issuecomment-1068061553
Look, I get it. The entity doing business as …
> Add volume for nginx cache

- docker-compose.yml
fix https://github.com/getsentry/self-hosted/issues/1343
Seems that docker compose 2.0.0 need types to be defined correctly and do no infer types automatically.
> fix "services.web.healthcheck.retries must be a number"

- .github/workflows/release.yml
In order to prevent a failed job run on forked repositories :)
For example:
https://github.com/aminvakil/self-hosted/runs/6905699181?check_suite_focus=true
It fails instantly right now with `Error: Input required and not supplied: token`, but why it should be run on forked repositories anyway?
> Run release a new version job only on getsentry

- docker-compose.yml
[nginx-1.22.0](https://nginx.org/en/download.html) stable version has been released, incorporating new features and bug fixes from the 1.21.x mainline branch  — including hardening against potential requests smuggling and cross-protocol attacks, [ALPN support](https://nginx.org/en/docs/stream/ngx_stream_ssl_module.html#ssl_alpn) in the stream module, better distribution of connections among worker processes on Linux, support for the PCRE2 library, support for OpenSSL 3.0 and SSL_sendfile(), improved [sendfile](https://nginx.org/en/docs/http/ngx_http_core_module.html#sendfile) handling on FreeBSD, the[ mp4_start_key_frame](https://nginx.org/en/docs/http/ngx_http_mp4_module.html#mp4_start_key_frame) directive, and more.
Look, I get it. The entity doing business as "Sentry" was incorporated …
> Bump nginx:1.22.0-alpine

- README.md
- install/_lib.sh
Fixes #941, also addresses the suggestion for a README tweak at the very bottom of https://github.com/getsentry/self-hosted/issues/1491#issuecomment-1159076555.
Look good to you, @aminvakil @glensc @Daniel15?
> Cleanup .env{,.custom} handling

- cron/Dockerfile
- docker-compose.yml
- install/build-docker-images.sh
> Improve installation through proxy

- docker-compose.yml
Fixes https://github.com/getsentry/self-hosted/issues/1556
> do not use gosu for snuba-transactions-cleanup and snuba-cleanup

- .github/workflows/test.yml
Then I'm going to implement https://github.com/getsentry/self-hosted/issues/1294#issuecomment-1180281521, but first this needs to be merged.
> Use docker-compose 2.7.0 instead of 2.2.3 in CI

- .github/ISSUE_TEMPLATE/problem-report.yml
make it easier for the user to copy the docker commands, when they are in the placeholder you cannot easily copy them (only by source code or by seeing the template)
Thanks
> added docker commands in the description

- _integration-test/run.sh
- install/error-handling.sh
- integration-test.sh
PR-ception. This PR updates the copy on #1679 (and fixes a bug in file pathing).
```
▶ Setting up error handling ...
Found a .reporterrors file. What does it say? no
```
```
▶ Setting up error handling ...
Hey, so ... we would love to find out when you hit an issue with this here
installer you are running. Turns out there is an app for that, called Sentry.
Are you okay with us sending info to Sentry when you run this installer?
y / yes / 1
n / no / 0
(Btw, we send this to our own self-hosted Sentry instance, not to Sentry SaaS,
so that we can be in this together.)
Here's the info we may collect:
- OS username
- IP address
- install log
- performance data
Thirty (30) day retention. No marketing. Privacy policy at sentry.io/privacy.
y or n? n
Understood. Your answer is cached in …
```
> Update copy and fix .reporterrors location

- cloudbuild.yaml
Add .reporterrors file with "no" for GCP run of e2e tests, required for dogfood change to skip user prompt
> fix(e2e tests): Add .reporterrors file for GCP run of e2e tests

- cloudbuild.yaml
For our PR check in self-hosted, we must checkout the branch of the PR.
https://console.cloud.google.com/cloud-build/triggers;region=global/edit/136f08d0-ed33-43a6-a009-55aed7a84bb3?project=sentryio
The `$BRANCH_NAME` is an env variable provided by GCP.
https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
> fix(e2e tests): Pull branch that initially triggers gcp build for PRs

- cloudbuild.yaml
- install/_lib.sh
- install/error-handling.sh
- integration-test.sh
Follow-up to #1679 to relax the non-interactive experience, closes #1693.
The proposal here is to default to not sending data for the non-interactive case, but with a notice that we will be forcing a decision in an upcoming version. This gives folks three months to notice and adjust, and it gives us some time to clean up configuration a bit.
> Default to not sending data to Sentry for now

- install/parse-cli.sh
- install/set-up-and-migrate-database.sh
The "user' in `--skip-user-prompt` is ambiguous. It's [intended](https://github.com/getsentry/self-hosted/blob/31767d27957cbba5281469df740379edd28df121/install/parse-cli.sh#L19) to refer to the initial Sentry user, but it's natural to think (as we saw at https://github.com/getsentry/self-hosted/issues/1693#issuecomment-1246604464) that it refers to the person operating Sentry, so that it would suppress _all_ interactive prompts during the installer.
```
$ SKIP_USER_PROMPT=1 ./install.sh --no-user-prompt --skip-user-prompt
▶ Parsing command line ...
WARNING The SKIP_USER_PROMPT variable is deprecated. Please use SKIP_USER_CREATION instead.
WARNING The --no-user-prompt flag is deprecated. Please use --skip-user-creation instead.
WARNING The --skip-user-prompt flag is deprecated. Please use …
```
> Rename flag to --skip-user-creation

- cloudbuild.yaml
- install/error-handling.sh
- install/parse-cli.sh
- integration-test.sh
The `.reporterrors` file is a somewhat idiosyncratic way to configure the sentry installer. We use environment variables and CLI flags for other configuration, we don't have a proper configuration file for the installer itself (vs. the runtime config files in `sentry/`). This PR switches to using envvars and CLI flags to configure whether we report to Sentry.
This also expands the scope of the ask to allow for future expansion into runtime data collection. We're starting with just the installer but we don't want to have to go through the consent exercise again in the future if we don't have to, better to ask once up front here.
> Switch from .reporterrors file to flag + envvar

- README.md
Mostly based on the prompt in the installer.
> Add section about error monitoring to the README

- install/error-handling.sh
add `-i` flag to keep STDIN open even if not attached
We were hashing an empty string before 😬
> Fix traceback hash for error monitoring

- .github/workflows/release.yml
uses sentry-cli to tag releases for us on our self-hosted instance
> Tag releases with sentry-cli

- .github/ISSUE_TEMPLATE/problem-report.yml
This was based on a suggestion by @aminvakil to make it easier to link issues on Github and Sentry.
> Request event ID in issue template

- install/check-minimum-requirements.sh
The function vergte here doesn't correctly use the return code in order to be used in version comparison. As a result, users are running older versions of docker compose. The issue with the largest number of events in our dogfood instance seems to be a result of folks using an older version of docker compose, then erroring out later during the turn things off script.
This fixes the issue here:
https://github.com/getsentry/self-hosted/issues/1706
> Fix minimum version requirements for docker and docker compose

- install/check-minimum-requirements.sh
One of our most common errors that we're seeing on self-hosted occurs when docker-compose doesn't exist. Our version check then throws an exception.
https://self-hosted.getsentry.net/organizations/self-hosted/issues/16/?query=is%3Aunresolved
This PR adds logic to ensure that we're able to find the version of docker compose and output an error msg to the user when docker compose does not exist.
> Check to see if docker compose exists, else error out

- install/_lib.sh
- install/error-handling.sh
For 22.10.0, we must enforce error reporting
> Enforce error reporting for self-hosted

- install/error-handling.sh
Right now, if someone presses ctrl+c, the event is sent to our dogfood instance. This removes that so we hopefully will see reduced noise
> Do not send event on INT signal

- .github/workflows/release.yml
uses the action-release/v1 to handle releases for dogfood since that's much easier!!
https://github.com/getsentry/action-release
Apparently, the version of the release is set earlier in the prepare release action and set as an environment variable `env.RELEASE_VERSION` so I'm using that. The `ignore_missing` and `ignore_empty` flags are set to avoid erroring out of release script.
> Fix sentry release for dogfood instance

- _unit-test/error-handling-test.sh
- _unit-test/snapshots/sentry-envelope-12345123451234512345123451234512
- install/build-docker-images.sh
- install/error-handling.sh
- jq/Dockerfile
In this PR, we change the send-event function to write out more information into the envelope we send via `sentry-cli`, particularly adding breadcrumbs with the end of the log and giving the stack trace in a format Sentry self-hosted can understand.
Fixes https://github.com/getsentry/team-ospo/issues/54 and https://github.com/getsentry/team-ospo/issues/53
Example issue with this formatting: https://self-hosted.getsentry.net/organizations/self-hosted/issues/227/?query=is%3Aunresolved
Also a cheat sheet for `jq` arguments:
- `-c` collapses to 1 line
- `-n` means null input (we're just constructing JSON, not mangling it)
- `-s` is "slurp" JSON lines into an array.
- `--arg` can be used to write object arguments
-  `--argjson` is like `--arg`, but takes JSON expressions as the argument!
> Upload end of log as breadcrumbs, use exceptions and stacktrace

- install/_lib.sh
- install/error-handling.sh
enforce error reporting again
https://github.com/getsentry/self-hosted/issues/1774
> Enforce error reporting

- .github/workflows/pre-commit.yml
Committed via https://github.com/asottile/all-repos
> ref: upgrade actions/setup-python to avoid set-output deprecation

- _unit-test/error-handling-test.sh
- _unit-test/snapshots/sentry-envelope-12345123451234512345123451234512
- install/error-handling.sh
This PR let's us more easily filter our issues by the error msg
1. Adds the actual error message as the error msg instead of the line we fail on
2. Adds context line to display the line we fail on
Before:
After:
> Add context line, error msg to envelope

- _unit-test/_test_setup.sh
- _unit-test/error-handling-test.sh
- install/build-docker-images.sh
- install/error-handling.sh
- jq/Dockerfile
It seems that we missed jq running in docker not working right -- all the environments we test on install it as a dependency of unit tests :/
This fixes things to correctly invoke the jq command and changes from CMD to ENTRYPOINT so the container works correctly.
Fixes https://github.com/getsentry/self-hosted/issues/1810
> Fix jq usage

- cloudbuild.yaml
Our contributor e2e tests are failing since we're trying to clone a branch that doesn't exist on `https://github.com/getsentry/self-hosted.git`. Their branches only exist on their forked repos, so we need to reflect that in our e2e tests.
Also tested this out with contributor PR's [here](https://github.com/getsentry/self-hosted/pull/1821)
> (fix): Fix contributor PR e2e tests

- install.sh
- install/check-minimum-requirements.sh
- install/parse-cli.sh
I've discovered that the check for SSE4.2 added in #361 fails on virtualization solutions other than KVM - possibly what the author of #1782 is having trouble with too.
Trying to install Sentry on a virtual machine running on a VMWare ESXi host ("ESXi 6.5 and later (VM version 13)"), it reports running on processors that _definitely_ [support SSE4.2](https://ark.intel.com/content/www/us/en/ark/products/120495/intel-xeon-gold-6154-processor-24-75m-cache-3-00-ghz.html):
```cat /proc/cpuinfo
model name	: Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz
```
But this is not reported in their `flags`.
In this case, this is likely to do with our VM cluster having old servers which really don't have SSE4.2 and so [VWMare targets the lowest possible instruction …
> Add --skip-requirements to install.sh and enable SUPPORTS_SSE42 override

- install/build-docker-images.sh
Fixes https://github.com/getsentry/self-hosted/issues/1847
I generated this list from things that have a `build` key, and those that use `x-sentry-defaults` (which builds an image as well).
> Build each service image individually

- install/install-wal2json.sh
This has been causing a lot of failures in CI in Sentry and elsewhere recently. Hopefully the failures are flakes and this will work around them.
> ref: Retry wal2json download in installer

- install/install-wal2json.sh
Retries were added to the `install-wal2json.sh` script in order to make CI pass, but the retries without any backoff cause rate limit issues. By default curl institutes exponential backoff
https://everything.curl.dev/usingcurl/downloads/retry
>  Using --retry-delay you can disable this exponential backoff algorithm and set your own delay between the attempts.
by not waiting any time between retries and launching CI jobs we shoot ourselves (and potentially other users) in the foot
> fix(CI): use default curl retry mechanism for wal2json install

- _unit-test/error-handling-test.sh
- install/build-docker-images.sh
- install/dc-detect-version.sh
- install/error-handling.sh
This fixes [errors early in the installer run not getting reported correctly](https://github.com/getsentry/self-hosted/issues/1884) and [jq's docker build not using the proxy config correctly](https://github.com/getsentry/self-hosted/issues/1871)
> ref: Move jq build to error-handling.sh, and use proxy config

- _integration-test/run.sh
- docker-compose.yml
Fixes https://github.com/getsentry/self-hosted/issues/1762
> ci: Check health of services after running integration tests

- scripts/post-release.sh
Adds a workaround for the error in https://github.com/getsentry/publish/actions/runs/4018136005
(not sure if this is fool-proof but it follows the suggestion in the output)
> Fix post-release.sh for `git pull`

- docker-compose.yml
Redis patched two CVEs in release `6.2.9`. We would like to update the Sentry container to apply those fixes:
https://github.com/redis/redis/releases/tag/6.2.9
After that release, it looks like they pushed a bug fix in `6.2.10` so it probably makes sense to bump up to that.
If there's anything I can do to help test or evaluate this change, let me know.
> Updates Redis to 6.2.10

- .github/workflows/lock.yml
There is no need to lock issues/PRs on forked repositories, also it faces this error lots of times:
`You have exceeded a secondary rate limit. Please wait a few minutes before you try again.`
Full list: https://github.com/aminvakil/self-hosted/actions/workflows/lock.yml
> Run lock issues/PRs only on getsentry

- nginx/nginx.conf
I was unable to access the `All Events` tab when looking at an issue. The browser showed an infinite loading screen. Devtools revealed 502 Bad Gateway responses for `/api/0/issues/:id/attachments/`. When I looked at the nginx log I found the following error: `upstream sent too big header while reading response header from upstream`.
This PR fixes the bad gateway error and makes the `All Events` tab work again.
Doesn't seem to be the only place affected by this issue either. I checked the logs for this specific error using `docker logs sentry-self-hosted-nginx-1 2>&1 | grep 'upstream sent too big header while reading response header from upstream'` and found another instance of this issue on the `/api/0/organizations/:name/sessions/` endpoint, but no idea where this is used in the …
> Add proxy buffer size config to fix Bad Gateway

- _integration-test/run.sh
- docker-compose.yml
- install/create-kafka-topics.sh
- sentry/sentry.conf.example.py
also confirmed this works w/ self hosted by running a webpage with our SDK pointed at the DSN of the self hosted server, then seeing it in the UI.
> feat(replays): add replays to self hosted

- .github/workflows/test.yml
Bumps action commit sha to fail test suite properly from typo fix here:
https://github.com/getsentry/action-self-hosted-e2e-tests/pull/7
> Bump self-hosted-e2e-tests action commit sha

- _integration-test/run.sh
Removes this integration test since it is broken. We will revisit in the future after ironing out how we want other teams to write integration tests for the stuff they own
> Remove broken replay integration test

- _integration-test/ensure-backup-restore-works.sh
- integration-test.sh
closes https://github.com/getsentry/self-hosted/issues/1918
Since there is a unit test in sentry already covering backup/restore, this is a more broad test. It tests these functionalities
1. Backup/restore is correctly writing any sort of data to the `backup.json` file. 
2. The export command doesn't throw an exception
3. The import command doesn't throw an exception
> Add backup/restore integration tests

- docker-compose.yml
We're on a mix of 5.5.7 and 5.5.13 in Saas (and 6.2.0 in Sentry dev).
> Bump Kafka version to keep up with SaaS

- docker-compose.yml
A new [self-hosted settings](https://github.com/getsentry/snuba/pull/3889) file was added in snuba to house all self-hosted specific settings. This is required as a part of the [Dataset Readiness State](https://www.notion.so/sentry/Dataset-Readiness-States-da12e741fe024a7c8916c7b36b94ed8f?pvs=4#07f225050b964afd9d6d6d68e617043c) project. Currently, the new settings file is an exact copy of the existing `settings_docker.py`, therefore there are no expected changes.
> ref(snuba): Use snuba self-hosted settings

- docker-compose.yml
- sentry/sentry.conf.example.py
Self hosted sentry limited in sourcemap external size, which can fetch and cache to 1Mb. 
> Remote file too large for caching
This is because `memcached` the maximum size of a value you can store in is 1 megabyte by default. But this can be fixed by `-I` param.
This PR allow to fetch and cache external sourcemaps for sentry up to 25Mb.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of …
> Support external sourcemaps bigger, than 1Mb

- docker-compose.yml
This is now removed, it's breaking CI now in sentry and snuba
> Remove commit-batch-size parameter

- scripts/_lib.sh
Saw this error in dogfood instance:
https://self-hosted.getsentry.net/organizations/self-hosted/issues/366/?project=3&query=is%3Aunresolved&referrer=issue-stream
So doing the same with our integration tests in `ensure-backup-restore-works.sh` to give all users read/write to the backup file so permission issues don't happen.
> Tweak permissioning of backup file in backup script to read/write for all users

- scripts/bump-version.sh
- scripts/post-release.sh
change symbolicator to use the same version as relay/sentry/snuba
closes https://github.com/getsentry/self-hosted/issues/2073
> Change symbolicator to use CalVer for release

- install/upgrade-postgres.sh
closes this 
https://github.com/getsentry/self-hosted/issues/2092
> Use docker compose exec to account for differences in container names for Postgres upgrade

- nginx/nginx.conf
This enables keepalive connections for both upstream blocks, following the best practices as recommended by nginx:
https://www.nginx.com/blog/avoiding-top-10-nginx-configuration-mistakes/#no-keepalives
> We recommend setting the parameter to twice the number of servers listed in the upstream{} block.
As there's only a single server in each block, we keep 2 idle connections.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my …
> Enable upstream keepalive

- scripts/_lib.sh
The docker-compose command was hard coded in backup and restore routines. Replaced with `$dc` variable instead
> Fixed docker compose issue in backup/restore

- .github/workflows/test.yml
- _integration-test/ensure-backup-restore-works.sh
This will uninstall docker compose v1.29 from CI so `docker-compose` cannot be used.
CI runs to indicate this is the case:
1. https://github.com/getsentry/self-hosted/actions/runs/4832862658/jobs/8612163711?pr=2114
1. https://github.com/getsentry/self-hosted/actions/runs/4832862658/jobs/8612163856?pr=2114
> Uninstall Docker Compose v1 from CI so it's not used for tests

- docker-compose.yml
Without these zookeeper and kafka fail to start on some systems. While web will consume ~8G of RAM.
Fixes: #40617
> adding ulimits for zookeeper, kafka, and web

- docker-compose.yml
I was upgrading my Sentry instance to the latest version, then I spent like 15 minutes wondering on why the Suggested Fix feature I [made the PR of](https://github.com/getsentry/self-hosted/pull/2115) is gone. I thought the Sentry team changed the logic of that. It turns out I made a typo. 
This is how I feel right now:
> fix(suggested-fix): key should be 'key', not 'token'

- docker-compose.yml
Ingest consumers will stop to support the `--all-consumer-types` option, and
instead will need to run separate instances for events, attachments, and
transactions.
See https://github.com/getsentry/sentry/pull/49957
> ref(compose): Separate ingest consumers

- scripts/bump-version.sh
fixes the bump version script, resulted in certain images not getting tagged in the 23.6.0 release
https://github.com/getsentry/self-hosted/commit/dbded584377d50a2545a98de5d0d53d204b369a0
> Fix bump version script

- .env
- README.md
closes https://github.com/getsentry/publish/issues/2383
The post release script didn't run successfully, so we'll need to manually perform these actions
> Release 23.6.1 cleanup

- docker-compose.yml
Context: https://github.com/getsentry/sentry/pull/50364
> ref: Move most consumers to unified consumer CLI

- docker-compose.yml
- install.sh
- install/create-kafka-topics.sh
Putting this up again since PR was reverted here: https://github.com/getsentry/self-hosted/pull/2223
Will need to investigate e2e test failures related to profiles topic not being found, resulting in CI being blocked on `getsentry/sentry`
> ref: Move all consumers to unified consumer CLI

- unit-test.sh
- turn off error reporting until we want to test it
- allow for running one test file at a time
> A couple unit testing improvements

- docker-compose.yml
LGTM the changelog: https://nginx.org/en/CHANGES-1.24
1.23 LGTM: https://nginx.org/en/CHANGES
and 1.22 only had a .1 with CVE fixes
1.25 is still a bit new, maybe we should wait before bumping: https://endoflife.date/nginx
> Update nginx to 1.25.1

- docker-compose.yml
I have read all changelogs between the two versions:
- https://github.com/maxmind/geoipupdate/releases
- https://github.com/maxmind/geoipupdate/releases?page=2
Since https://github.com/maxmind/geoipupdate/releases/tag/v4.8.0 there is two new ENVs to avoid overriding the entrypoint 
@chadwhitacre you did comment on #766 back in the day https://github.com/getsentry/self-hosted/pull/766/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3
Should we use ENVs now ?
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my …
> Update geoipupdate to 5.1.1

- scripts/_lib.sh
Looks like this was missed in #2029, running reset.sh now runs the bash `reset` and just resets the console 😅
> Fix command called in reset script

- docker-compose.yml
- sentry/sentry.conf.example.py
Let's not store this key in the env variables to reduce the risk of potentially leaking secrets.
> Move open ai key from env variables

- docker-compose.yml
The nc -q option is failing for some users as seen [here](https://github.com/getsentry/self-hosted/issues/2260). Seems like -q does this from [docs](https://docs.oracle.com/cd/E86824_01/html/E54763/netcat-1.html) and seems safe to remove:
After receiving EOF on stdin, wait for specified number of seconds and quit.
> Remove nc -q option

- nginx/nginx.conf
With release 23.7.0, the upstream sentry@23.7.0 upgraded Django to 3.2.20, a breaking change for that dependency. This introduced a number of bugs into self-hosted, including one where the Content-Disposition response header is now set by Django in a manner that is illegible to Safari, as documenting in https://code.djangoproject.com/ticket/31082.
This change modifies the default nginx config to override this header with the simpler `inline` setting, allowing Safari to properly decompress gzipped resources like CSS and Javascript bundles.
Fixes #2285
> Resolve Safari Content-Disposition header bug

- docker-compose.yml
this PR will update GeoIPUpdate of the v5.1.1 to v6.0.0.
Release: 
https://github.com/maxmind/geoipupdate/releases/tag/v6.0.0
> Update GeoIpUpdate to v6.0.0

- _integration-test/run.sh
[CI is failing](https://github.com/getsentry/self-hosted/actions/runs/5754490765/job/15600711229) since it thinks that `fixture-custom-ca-roots` has errored out, when it fact it has just simply been removed as a part of testing. Not sure why this is happening all of the sudden, but this should be safe.
This is blocking 23.7.2 and even after changing the images in the .env to 23.7.1, CI still fails.
> Ignore fixture-custom-ca-roots service in integration test

- docker-compose.yml
- install/create-kafka-topics.sh
- sentry/sentry.conf.example.py
Yes, I know...more containers. 😬
adds issue platform infra for https://github.com/getsentry/self-hosted/issues/2269
> Add issue platform infra

- docker-compose.yml
Checking kafka topics is a more proper way to check that kafka server is up and running, rather than just checking opened port. You should treat this as `pg_isready` command.
Before this patch, step with `bootstrap-snuba`, fails on topics creation with error:
```
Failed to create topic events (and many others)
Traceback (most recent call last):
File "/usr/src/snuba/snuba/utils/manage_topics.py", line 31, in create_topics
future.result()
File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
return self.__get_result()
File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
raise self._exception
File "/usr/local/lib/python3.8/site-packages/confluent_kafka/admin/__init__.py", line 113, in _make_topics_result
result = f.result()
File …
```
> change health check for kafka service

- nginx/nginx.conf
This is causing downloads to work unexpectedly.
https://github.com/getsentry/self-hosted/issues/2377
> Remove nginx content-disposition hack for safari

- .github/workflows/test.yml
Docker compose 2.21.0 broke the `ps --format=json` output.
> fix: e2e test jq bug

- docker-compose.yml
Capturing some security fixes by updating to 6.2.13 for Redis [changelog](https://raw.githubusercontent.com/antirez/redis/6.2/00-RELEASENOTES).
This will remediate [CVE-2022-24834](https://redis.com/blog/security-notice-heap-overflow-vulnerabilties/).
> Update Redis container image to 6.2.13

- docker-compose.yml
Bumps the nginx container to the latest available 1.25 version.
Address part of #2481
> deps: bump nginx to 1.25.2

- _unit-test/create-docker-volumes-test.sh
- docker-compose.yml
- install/create-docker-volumes.sh
- install/turn-things-off.sh
This reverts commit a177142f3569dbd05dc6934eb13d1a40f615bb07.
There isn't a clean way to migrate existing kafka clusters to KRaft mode right now. This will need to be revisited in the future
> Revert "feat: upgrade to zookeeper-less kafka (#2445)"

- docker-compose.yml
Deprecated since https://github.com/getsentry/snuba/pull/4915
> snuba: Remove deprecated CLI arg

- install/detect-platform.sh
Upgrades clickhouse for self-hosted users. Tested it out on our own self-hosted Sentry instance and it seems to work smoothly 🤞
> Upgrade Clickhouse to 21.8

- sentry/config.example.yml
- sentry/sentry.conf.example.py
Closes #2546 
I am aware that Discord integration hasn't gotten to GA yet. But I think it's usable enough and people are willing to use it.
If it's already at GA, we'd need to update this:
https://github.com/getsentry/develop/blob/f0bb60e09ca723e7f9be1ab1d5d3a3259d4a1ff7/src/docs/integrations/discord/index.mdx#L67-L75
> feat: provide a toggle to enable discord integration

- docker-compose.yml
Recently this error started appearing in dev environments on Apple silicon chips. 
```
▶ Setting up / migrating database ...
smtp Pulling
no matching manifest for linux/arm64/v8 in the manifest list entries
Error in install/set-up-and-migrate-database.sh:13.
'$dcr web upgrade' exited with status 18
```
This is a workaround for that
> Patch for dev self-hosted environments

- _integration-test/ensure-backup-restore-works.sh
- _integration-test/ensure-sentry-admin-works.sh
- sentry-admin.sh
`sentry-admin.sh` is just a bash wrapper around some admin commands that are already technically exposed in the `web` container, though a bit hard to find today. This command just forwards the `sentry` command-line administration tool out from the container onto the host machine, slightly editing the help docs to make it a bit easier to use in the process.
> feat: Add sentry-admin.sh tool

- .github/ISSUE_TEMPLATE/release.yml
This should make it easier to start releases.
> Make a release issue template

- nginx/nginx.conf
This fixes warnings from nginx and creating temporary files on disk
```
[warn] 46#46: *133550 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000011816, client: 172.30.0.1, server: , request: "POST /api/53/envelope/?sentry_key=-&sentry_version=7&sentry_client=sentry.javascript.vue%2F7.80.0 HTTP/1.0", host: "-", referrer: "-/"
```
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, …
> Nginx client request body is buffered to a temporary file

- docker-compose.yml
- install/create-kafka-topics.sh
- sentry/sentry.conf.example.py
This PR does a few things to enable crons in self-hosted.
1. feature flag flipped on for crons
2. ingest consumer added for crons
3. crons kafka topic added
closes https://github.com/getsentry/self-hosted/issues/1993
> Enable crons

- cron/Dockerfile
Fix inverted logic for http_proxy condition in cron container configuration.
Closes https://github.com/getsentry/self-hosted/issues/2725
> Fix apt config generation when http_proxy is set (#2725)

- install/set-up-and-migrate-database.sh
should fix this: https://github.com/getsentry/self-hosted/issues/2758
> Fix groupedmessage indexing error

- install.sh
- install/check-memcached-backend.sh
Fixes https://github.com/getsentry/self-hosted/issues/2728.
> Adapt to new memcached backend in Django

- install/set-up-and-migrate-database.sh
This improves the logic to wait for postgres server to be up and running. It also fixes a typo 😬
It seems like using `pg_isready` in the install script was not a reliable way to wait for the postgres server to be up and ready to accept connections. So, I used a few lines that were previously working from the `upgrade-postgres.sh` script. Additionally, the `exec` command was missing when removing the specific db index causing issues.
Follow up to https://github.com/getsentry/self-hosted/issues/2758
> fix: DB migration script

- install/set-up-and-migrate-database.sh
Now fixes the groupedmessage indexing issue for a wider variety of users as reported in https://github.com/getsentry/self-hosted/issues/2780, particularly the one related to this error:
```
ERROR:  cannot drop index sentry_groupedmessage_project_id_id_515aaa7e_uniq because constraint sentry_groupedmessage_project_id_id_515aaa7e_uniq on table sentry_groupedmessage requires it
HINT:  You can drop constraint sentry_groupedmessage_project_id_id_515aaa7e_uniq on table sentry_groupedmessage instead.
```
> Tweak postgres indexing fix

- docker-compose.yml
This made it directly to master...perhaps we are missing some branch protection rules
> Revert changes in 3067683f6c0e1c6dd9ceb72cb5155c1dbf3bf501

- install/set-up-and-migrate-database.sh
This provides support for sql commands run during the install script to span over custom db installs
> chore: Use django ORM to perform sql commands

- sentry/sentry.conf.example.py
Some people are confused about the way the configuration just put `example.com` and not putting any `https://` prefix on it. That's on me though 😬
> chore: provide clearer csrf url example

- docker-compose.yml
This adds the snuba rust consumers to self-hosted
> Add snuba rust consumers

- nginx/nginx.conf
Setting the proxy_buffering directive to “off” is a common mistake because it can cause performance issues and unexpected behavior in NGINX. When proxy buffering is disabled, NGINX receives a response from the proxied server and immediately sends it to the client without storing it in a buffer. This can cause problems if the response is large or if the connection between NGINX and the client is slow, because it can result in increased memory usage and potentially lead to request timeouts.
To avoid this mistake, it is recommended to always enable proxy buffering in NGINX.
Resolves https://github.com/getsentry/self-hosted/issues/2836
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some …
> Enable proxy buffering in nginx

- .github/workflows/test.yml
- _integration-test/run.sh
- install/error-handling.sh
- integration-test.sh
- test.sh
This PR adds a couple of improvements to our integration test pipeline.
1. Parallelizes some tests, runtime was 23+ minutes. Now this is decreased to <18 minutes
2. Reports failures to Sentry project
In order to report flakes, I wanted to cut down the time it takes to actually run these tests. Given that with 20 min tests, it could take an hour if the tests flake twice.
> Integration test improvements

- sentry/sentry.conf.example.py
Fixes standalone span ingestion not working on relay by adding missing organizations:standalone-span-ingestion flag to default config.
> fix(spans): Adds organizations:standalone-span-ingestion flag to default config

- .github/ISSUE_TEMPLATE/problem-report.yml
Adds an example to get the version of docker compose. 
Since the command to get the version of **Docker** is `docker --version` you would expect the command for **Docker Compose** to be `docker compose --version` but for whatever reason it's not, so people probably waste time trying to figure out what the proper command is.
> Add example to docker compose version in problem report

- docker-compose.yml
Bump memcached and redis to their latest patch versions to resolve known vulnerabilities.
> chore(deps): bump memcached and redis to latest patch versions

- sentry/sentry.conf.example.py
fixes: https://github.com/getsentry/sentry/issues/69456
> fix(performance): Add spans-first-ui flag to enable starfish/performance module views in ui

- .github/workflows/sample-test-runs.yml
let's keep this on during the workday for sampling purposes, run e2e tests 100+ times before getting rid of this workflow
I think then we can use something like https://github.com/fchimpan/gh-workflow-stats for some useful stats
> Sampling: Run e2e tests every 5 minutes

- .github/workflows/test.yml
This additional coverage will hopefully help catch some bugs introduced from upgrading self-hosted. This is particularly useful for infrastructure upgrades such as clickhouse, kafka, or zookeeper
> Add upgrade test

- install/upgrade-clickhouse.sh
For large instances of clickhouse, we should probably have this
> Add clickhouse healthchecks to upgrade

- docker-compose.yml
--no-skip-writes doesn't do anything. The consumers now writes to clickhouse by default.
> remove ref to skip writes

- install/update-docker-volume-permissions.sh
Close https://github.com/getsentry/self-hosted/issues/3030
> fix: Make docker volume script respect compose project name

- sentry/config.example.yml
> Typo in config.example.yml

- install/update-docker-volume-permissions.sh
Avoid using a hardcoded path to docker root dir. Instead, fetch the path dynamically and use it.
Use case: folks using a non standard docker root dir.
> Fix install: use dynamic docker root dir instead of hardcoded one

- clickhouse/config.xml
User mentioned this comment will be helpful when using a custom upgrade process for clickhouse:
https://github.com/getsentry/self-hosted/issues/3001#issuecomment-2126662019
> chore: Add comment explaining the one liner in clickhouse config

- sentry/sentry.conf.example.py
We split the feature flags for span ingestion in 3 different buckets:
- indexed spans
- metrics extraction for some modules
- metrics extraction for add-on modules
This PR will make sure all 3 features are now enabled in self-hosted.
> ref(spans): Add new feature flags needed

- .github/workflows/test.yml
- install/update-docker-volume-permissions.sh
Previously, we were using `sudo -E ./install.sh` to get around permissioning issues in CI when setting docker volume permissions. Using this approach, sudo is no longer needed in the install script to modify docker permissions if users do not have access to the docker volume directories
> Different approach to editing permissions of docker volumes

- .github/workflows/test.yml
- README.md
- install/_min-requirements.sh
Closes #3070
docker compose down <service> is now required in https://github.com/getsentry/self-hosted/blob/master/install/upgrade-clickhouse.sh#L27.
Here is the corresponding docker compose Changelog: https://docs.docker.com/compose/release-notes/#bug-fixes-and-enhancements-19
I was running the install script using docker compose v2.18.1, and the install failed with:
```
Container sentry-self-hosted-clickhouse-1  Running
sentry-self-hosted-clickhouse-1   clickhouse-self-hosted-local   "/entrypoint.sh"    clickhouse          4 minutes ago       Up 31 seconds (healthy)   8123/tcp, 9000/tcp, 9009/tcp
unknown command "clickhouse" for "docker compose down"
Error in install/upgrade-clickhouse.sh:23.
'$dc down clickhouse' exited with status 1
-> ./install.sh:main:25
--> …
```
> Update minimum docker compose requirement

- docker-compose.yml
- install/create-kafka-topics.sh
We now process tasks via Kafka consumers instead of celerybeat. This needs to be added to self-hosted as well
> feat: Add crons task consumers 

- docker-compose.yml
talked to @lynnagara, ingest consumers are not run with `--no-strict-offset-reset`, but post process forwarders are
This should fix https://github.com/getsentry/self-hosted/issues/2951
> Update consumer flags

- requirements-dev.txt
`1.39.2` -> `2.4.0`
No code changes necessary, the API we're using in the integration tests has not changed in 2.x.
> Bump Python SDK version used in tests

- docker-compose.yml
should resolve https://github.com/getsentry/self-hosted/issues/3107 and perhaps https://github.com/getsentry/self-hosted/issues/3115 is an issue that came from switching the OS.
> Use non-alpine postgres

- sentry/sentry.conf.example.py
Closes #3145
After this is merged, we should create a new patch release 24.6.1 to handle that specific issue, since during the time of the self-hosted release, the Insights team ported a few changes from Performance -> Insights.
Also removes `spans-first-ui` per this PR https://github.com/getsentry/sentry/pull/72255
> feat: add insights feature flags

- sentry-admin.sh
`sentry-admin.sh` only works when called from the working directory and not using its absolute path.
This change makes it also callable using its absolute path.
> Update sentry-admin.sh to select its own working directory

- install/set-up-and-migrate-database.sh
We want to avoid situations like what happened in https://github.com/getsentry/self-hosted/issues/3167
> Check postgres os before proceeding with install

- docker-compose.yml
Adding this missing consumer, this is a repeat of https://github.com/getsentry/self-hosted/pull/2757
> feat(generic-metrics): Add gauges to docker compose, re-try

- .env
- .github/workflows/test.yml
- docker-compose.yml
- sentry/sentry.conf.example.py
This does a couple of things:
Sets the default docker compose profile to "feature-complete". This way, users can opt in to using errors-only self-hosted if they want, otherwise nothing changes. 
To enable errors only self hosted
Change .env file
SENTRY_SELF_HOSTED_ERRORS_ONLY = True
COMPOSE_PROFILES = errors-only
> Add errors only self-hosted infrastructure

- sentry/sentry.conf.example.py
This was a bug, I had `SENTRY_SELF_HOSTED_ERRORS_ONLY = env("COMPOSE_PROFILES") != "feature-complete"` locally in my sentry.conf.py when testing
relevant issue: https://github.com/getsentry/self-hosted/issues/2533
> Fix: errors only config flag

- sentry/sentry.conf.example.py
In the Sentry UI you can get a "Loader Script", however currently this services a JS files that results in a console warning that the loader "isn't working anymore". However this is not very apparent from the UI and still works great on SaaS. 
What the loader script currently serves (with some other boilerplate):
```js
console.warn("The Sentry loader you are trying to use isn't working anymore, check your configuration.");
```
This has been discussed at length in multiple places and venues (most recent: getsentry/sentry#22715). And the conclusion looks to be that it's very hard to enable for self-hosted. @aldy505 event created a super cool container to server the needed files: https://github.com/getsentry/sentry/issues/22715#issuecomment-2129862063.
However... I decided to go digging …
> Use CDN by default for JS SDK Loader

- docker-compose.yml
- sentry/sentry.conf.example.py
Closes #2646
This is based on https://develop.sentry.dev/feedback-architecture/ and some other stuff that I've used since User Feedback is in beta.
> feat: enable user feedback feature

- sentry/enhance-image.example.sh
this package does not exist on modern debians, the headers are already available in the docker image anyway
resolves #3226
> remove python-dev

- .github/ISSUE_TEMPLATE/release.yml
Remove sentry-docs and develop docs, as they're not needed for a self-hosted release.
> Update release template

- .env
- _unit-test/js-sdk-assets-test.sh
- docker-compose.yml
- install.sh
- install/create-docker-volumes.sh
- install/setup-js-sdk-assets.sh
- nginx/nginx.conf
- sentry/sentry.conf.example.py
Since this is hanging on my branch, I guess I'll make it out here. A part of making the JS SDK loader script available on the self-hosted sentry. Refer to https://github.com/getsentry/sentry/issues/22715.
Since not everyone is happy on hosting the JS SDK themself, therefore I made it into a feature flag. Set `SETUP_JS_SDK_ASSETS=1` on the `.env` file to enable the script. Also set `SETUP_JS_SDK_KEEP_OLD_ASSETS=1` to never delete (or basically cleanup) previous JS SDK version.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and …
> ref: allow hosted js sdk bundles

- sentry/config.example.yml
I don't remember if it's on Discord or on Github issues, but someone had a problem setting this up and although it's Django's behavior, not everyone code in Django.
> docs: explicitly specify `mail.use-{tls,ssl}` is mutually exclusive

- sentry/Dockerfile
- sentry/enhance-image.example.sh
- sentry/entrypoint.sh
- sentry/requirements.example.txt
I updated the old links to the repository documentation that were changed in PR #3307  (Issue #1996 )
I set the link to the Sentry domain as I saw in other parts of the application. If necessary, I can change them to the links from the MK file in the repository.
https://github.com/getsentry/sentry-docs/blob/master/develop-docs/self-hosted/index.mdx#enhance-sentry-image
Thank you.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my …
> chore: replace old URLs of the repo with the new docs

- CONTRIBUTING.md
- requirements-dev.txt
- sentry-admin.sh
Currently sentry-admin.sh script saves the output of the command to a separate variable. This makes the command "freeze" if it requires any input from the user (like sentry-admin.sh restore). The change should provide the output directly to the shell.
Also changed contributing.md as it seemed outdated and updated requirements-dev.txt with the missing `cryptography` package.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my …
> fix(sentry-admin): Do not wait for command finish to display output

- sentry/sentry.conf.example.py
Reverts getsentry/self-hosted#3402
This is to get #3397 back.
> Revert "Revert "ref(feedback): remove issue platform flags after releasing issue types""

- _unit-test/js-sdk-assets-test.sh
- install/setup-js-sdk-assets.sh
- unit-test.sh
Hopefully fixes https://github.com/getsentry/sentry/issues/22715#issuecomment-2458066842
> fix(loader): provide js sdk assets from 4.x

- docker-compose.yml
Will close https://github.com/getsentry/self-hosted/issues/3366
Improves the current redis healthcheck to also factor in loading dataset in memory
> feat(healthcheck): Improve redis healthcheck

- docker-compose.yml
- sentry/sentry.conf.example.py
Being removed and sunset in favor of AI suggested solution powered by seer.
Refer to https://github.com/getsentry/sentry/pull/58703 and https://github.com/getsentry/sentry/pull/81093
> ref: remove suggested fix

- .github/ISSUE_TEMPLATE/problem-report.yml
To remove roundtrip of asking people "what's your machine specification look like?"
> chore(issue-template): ask for machine specification and provide link to security policy

- docker-compose.yml
Follow up to https://github.com/getsentry/self-hosted/pull/3427#issuecomment-2518128717 where we created and mounted a custom Redis config only to not use it :facepalm:
> fix(redis): Actually use custom config

- _integration-test/test_run.py
- nginx.conf
Our default fallback, `_assets`, assumes we use a CDN which is not the case on self-hosted. This patch adds a stop-gap fix for front-end URLs asking for this path.
Should fix #3479 and #3470.
> fix(nginx): _assets should rewrite to _static/sentry/dist

- relay/config.example.yml
See https://github.com/getsentry/self-hosted/issues/3330
> chore(relay): provide opt-in max_memory_percent config as workaround for failing healthcheck

- .env
- sentry/sentry.conf.example.py
Some people are missing the `COMPOSE_PROFILES` in their .env file, Hopefully this clears everything up (and make the `SENTRY_SELF_HOSTED_ERRORS_ONLY` variable stands out on the config file.
> chore: clearer message for errors-only mode

- .github/workflows/test.yml
- docker-compose.yml
- install/geoip.sh
- install/set-up-and-migrate-database.sh
- install/upgrade-clickhouse.sh
- install/upgrade-postgres.sh
- install/wrap-up.sh
- sentry-admin.sh
`geoipupdate` is not used by any other service nor it is needed for any
service to run. Moreover, it is a one-shot command, causing
`docker compose up --wait` to fail when it exits with a non-zero status.
This happens when one has not yet set up their credentials and they may
choose to never do this.
This PR removes `geoipupdate` from the `docker-compose.yml` file and
moves the command directly into the geoip related script. One may run
this whenever they want to update their GeoIP database.
This PR needs an accompanying docs change.
It also has the side-effect of making integration tests slightly faster (due to the initial `docker compose up --wait`), and more reliable as we used to rely on the implicit `docker compose run web` from the `sentry_admin` test. This also skewed the test run …
> ref(geoip): Remove geoipupdate from compose

- install/bootstrap-snuba.sh
I think we split these actions in the past due to some lack of options for them to work together properly. Right now looks like `bootstrap` would automatically migrate and propagates the `force` flag.
> ref(snuba): Combine bootstrap & migrate for faster bootstrap

- install.sh
- install/update-docker-volume-permissions.sh
- install/wrap-up.sh
Since the last hard stop is at 24.8.0, which uses zookeeper-less kafka (kRAFT), this can be safely removed
Closes #2489
> chore: Remove everything zookeeper

- .github/workflows/test.yml
- docker-compose.yml
- install/set-up-and-migrate-database.sh
Follow up to #3488
A new record: 2m 8s for installing self-hosted:
> ci: Skip DB ops during install completely on cache hit

- .github/workflows/test.yml
Docker Compose is much more robust nowadays compared to the past where we had to maintain tests for both v1 and v2 and then a specific version of v2. Hence, we are removing tests for the older versions of Docker Compose with this patch. We also remove the separate tests for customizations and w/o customizations as the one with customizations should cover the one without them anyway. This reduces the CI workload to 25% of what it was
> ci: Only test on compose 2.26 w/ customizations

- .github/workflows/test.yml
- action.yaml
This is an initial transitionary patch before landing #3516. Once we land this, we will update users of the old action to use this one and remove that repo. Then land #3516 safely.
Great thing is, with this patch and the subsequent update to getsentry/action-self-hosted-e2e-tests to use this one, all the repos would be using the Docker Volume caching we introduced in #3488.
> ci: Move e2e test action into the repo

- action.yaml
See errors on getsentry/snuba#6746
> fix: Fix the new e2e action to be portable

- install/wrap-up.sh
See https://github.com/getsentry/self-hosted/issues/3451#issuecomment-2556417604
> chore: include regular env file on wrap-up

- .github/workflows/test.yml
- action.yaml
Instead of using direct image hashes, only use hashes from migrations folders for each respective image for cache key generation. Should increase cache hit rate significantly as we don't have migrations much.
Also swaps the key order from `sentry-snuba` to `snuba-senry` assuming Snuba has less frequent migration additions.
> ci: Less volatile cache keys

- .github/workflows/test.yml
- action.yaml
- install/upgrade-clickhouse.sh
See https://github.com/BYK/docker-volume-cache-action
> ci: Use generic Docker volume cache action

- action.yaml
We need to care about more than just src/sentry/migrations. We will need to account for files in src/sentry/**/migrations/*
Taken from https://github.com/getsentry/sentry/blob/afd74698180066223dee53991b7db26ca80ea3e5/.github/file-filters.yml#L90
> fix: Caching of sentry migrations should cover additional folders

- action.yaml
self-hosted CI runs in other repos are failing since they're not using the right path for getting docker compose version as seen in https://github.com/getsentry/snuba/actions/runs/12818778331/job/35745427857?pr=6784
> fix: Use correct path for get compose action

- _integration-test/test_02_backup.py
- sentry-admin.sh
I _think_ we can get away with this but let's see what the CI thinks. If it passes, it should save us another minuter or two.
Another record: 8m 49s
> ci: Remove obsolete `dcr up -w` from import test

- sentry/config.example.yml
Not sure why, but `system.url-prefix` and `system.internal-url-prefix` were not under `System Settings` in sentry/config.example.yml
The PR simply moves the three lines to the right section.
> refactor: move system.url-prefix under systems settings section

- get-compose-action/action.yaml
Fixes https://github.com/getsentry/self-hosted/issues/3596.
> Bump docker-compose 2.33.1

- install/dc-detect-version.sh
With #3595, we now check both `docker-compose` and `docker compose` versions so this patch removes the implicit fallback to `docker-compose` for `$dc_base` and makes it explicit.
> ref: Less complicated docker compose detection

- install/dc-detect-version.sh
Thanks to @hubertdeng123 in https://github.com/getsentry/self-hosted/pull/3604#discussion_r1982135356 for pointing this out.
```
$ docker-compose --version
Docker Compose version 2.33.1
$ docker-compose --version --short
2.33.1
```
> Add --short to docker-compose version

- install/_lib.sh
- install/check-minimum-requirements.sh
- install/dc-detect-version.sh
If the docker-compose version was less than the minimum required version, the install script would error out like this:
```
❯ ./install.sh
<snip>
▶ Checking minimum requirements ...
Found Docker version 27.5.1
install/check-minimum-requirements.sh: line 17: install: unbound variable
```
With this patch, the script correctly identifies the out-of-date docker-compose version and bails out with a more helpful message:
```
❯ ./install.sh
<snip>
▶ Checking minimum requirements ...
Found Docker version 27.5.1
FAIL: Expected minimum docker compose version to be 2.132.2 but found 2.32.4-desktop.1
```
(Note that `2.132.2` is not a real docker-compose version; I've edited the `install/_min-requirements.sh` file locally for testing, to make the installed version out of date.)
Also tested that the …
> Fix unbound variable error in install script

- docker-compose.yml
- relay/config.example.yml
- sentry/sentry.conf.example.py
- symbolicator/config.example.yml
In accordance with https://github.com/getsentry/sentry-docs/pull/12660
> feat: provide monitoring-related configurations

- _unit-test/js-sdk-assets-test.sh
- install/setup-js-sdk-assets.sh
Closes https://github.com/getsentry/self-hosted/issues/3614
> fix: js-sdk directory/file permission should be set correctly

- sentry/config.example.yml
Add example config for Google Auth in sentry/config.example.yml
```
###############
###############
```
> docs(config): add example config for Google Auth in sentry/config.example.yml

- install/_min-requirements.sh
Using the [errors-only](https://develop.sentry.dev/self-hosted/experimental/errors-only/) profile, fewer resources are required. About 2 times.
> Minimum requirements for 'errors-only' profile

- install/upgrade-clickhouse.sh
Using `$dc` instead of `docker compose` ensures users which still rely on `docker-compose` can execute `upgrade-clickhouse.sh`.
Thanks to @csvan for bringing this up in https://github.com/getsentry/self-hosted/issues/3630#issuecomment-2745377412.
> Use dc variable in clickhouse step

- relay/config.example.yml
Although a fix is being rolled out, that does not mean every relay instance would suddenly be fixed. We would need to still provide a workaround for people to try out. Refer to this specific issue comment: https://github.com/getsentry/self-hosted/issues/3330#issuecomment-2751092219
> chore(relay): specify spool.enveloppe.max_backpressure_memory_percent configuration for handling relay's failing healthcheck

- _integration-test/test_01_basics.py
This small PR fixes the `datetime` deprecation warnings which you can find in the CI logs:
```python
/home/runner/work/_actions/getsentry/self-hosted/master/_integration-test/test_01_basics.py:303: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
```
> Resolve datetime deprecation warnings

- install.sh
- install/_lib.sh
- install/_logging.sh
- install/dc-detect-version.sh
- sentry-admin.sh
Sentry Admin Script always fail because of missing import of lib script.
Fixes #3700.
> Add missing lib script to sentry-admin.sh

- sentry/sentry.conf.example.py
Some feature flags regarding starfish and performance has been removed from the codebase. We should tidy up the ones defined on self-hosted to avoid confusion.
> chore: prune removed feature flags on main repository

- requirements-dev.txt
For some reason we're installing an alpha version of the Python SDK in the integration test. This breaks pytest-sentry (we're working on a fix there). Temporarily restricting Python SDK to current stable major.
> tests: Install version 2.x of Python SDK

- .github/workflows/shellcheck.yml
- install/_lib.sh
Hello.
I would like to add [shellcheck](https://www.shellcheck.net/) linter for install scripts.
To avoid messing with https://github.com/getsentry/self-hosted/pull/3673 podman PR (and to not edit all scripts at once) this action only checks `install/_lib.sh`
I'm willing to slowly add all other `*.sh` scripts too.
Some trade-offs I made:
1. checks restricted to `install/_lib.sh` but action runs on any `**.sh` change.
1. [SC1090](https://www.shellcheck.net/wiki/SC1090) and [SC1091](https://www.shellcheck.net/wiki/SC1091) disabled because I don't have full context on how env-sources are used
1. `ensure_file_from_example()` excluded as kinda false-positive, pure bash solution won't be more readable I suppose
1. direct shellcheck run is used because tool is preinstalled and it's output could …
> add shellcheck action to lint bash scripts

- docker-compose.yml
Migrated from `tianon/exim4` image that does not support `arm64` to `registry.gitlab.com/egos-tech/smtp` that does. Also both use `exim4` under the hood so no changes to the volumes were necessary.
The initial suggestion was to migrate to `ixdotai/smtp`, but it [seems to be deprecated](https://github.com/ix-ai/smtp?tab=readme-ov-file#deprecation-notice).
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under …
> feat: migrate to arm64-compatible smtp image

- .github/workflows/shellcheck.yml
- scripts/_lib.sh
- scripts/bump-version.sh
- scripts/restore.sh
- unit-test.sh
- workstation/200_download-self-hosted.sh
Hello!
Another batch of shellcheck fixes, warnings can be seen [here](https://github.com/doc-sheet/self-hosted/pull/3/files#diff-db1fee65b65ba2eaf52a4f3f66a6ad40230ff85501acc04885eadf7b1a3642c7)
I did my best to find out is anyone was working with changed files.
Ignores of [SC1090](https://www.shellcheck.net/wiki/SC1090), [SC1091](https://www.shellcheck.net/wiki/SC1091) replaced with `--external-sources` flag.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, …
> enable shell linter for more scripts

- _integration-test/test_01_basics.py
This test has been incredibly flakey as of late which is impacting the Relay CI, as we run these test there as well.
This now tries to mitigate the flakeyness by increasing the timeout.
If you think there is a better way to approach this please do not hesitate to comment, same for if you think this is not the correct way to tackle the flakeyness.
Note: This test also seems to be flakey in self-hosted, this can be seen by search for the test name in github, since codecov will post a comment with the name of the failed test: https://github.com/search?q=org%3Agetsentry+test_01_basics.py&type=pullrequests
> fix: Increase timeout for flakey test

- sentry/sentry.conf.example.py
The `trace-view-v1` has been removed here: https://github.com/getsentry/sentry/pull/94474
Since EAP items consumer has been enabled on self-hosted, it makes sense to enable `visibility-explore-view` while currently `performance-trace-explorer` is being phased out on SaaS.
Current SaaS also have `performance-trace-explorer` disabled. This information is gathered from Tony Xiao.
> feat: Swap `trace-view-v1` feature flag with `visibility-explore-view`

- .github/workflows/test.yml
- action.yaml
It's hard to debug docker compose failure on other repositories since they can't see the `docker compose ps` and `docker compose logs`. One problem occurred here: https://github.com/getsentry/relay/pull/4940
This PR aims to provide both commands if failure happens.
> feat: inspect docker compose failure on self-hosted e2e action

- action.yaml
This one is missing. First seen here: https://github.com/getsentry/uptime-checker/actions/runs/16429015462/job/46426515654
> fix(action): missing project directory path for failure inspection

- sentry/config.example.yml
Happened today on Discord where a user changed internal-url-prefix and broke their instance. I think this should be stated clearer for new users and for non-native English speakers.
> docs: clearly state that `system.internal-url-prefix` shouldn't be changed

- .github/workflows/test.yml
> [!NOTE]
> This was me playing around with GH Copilot Security. Feel free to merge if you think this helpful. Otherwise, please just close it.
Potential fix for [https://github.com/getsentry/self-hosted/security/code-scanning/12](https://github.com/getsentry/self-hosted/security/code-scanning/12)
To fix this issue, add a `permissions:` block at the top level of the workflow file, directly under the `name:` line and before the `on:` block. This block should specify the minimal permissions required for the jobs in this workflow. Since the jobs only perform test-related tasks and do not push code or manage issues, setting `contents: read` is the safest and most appropriate minimal permission set. No changes to existing functionality are necessary, as the jobs should not require write …
> Potential fix for code scanning alert no. 12: Workflow does not contain permissions

- sentry/sentry.conf.example.py
Disable taskworkers for self-hosted until the documentation has been published.  What I'm not clear on is how to define this option for _existing_ self-hosted installs.
Refs getsentry/sentry#96966
> feat: Continue using celery in self-hosted for now

- docker-compose.yml
Fix for https://github.com/getsentry/self-hosted/issues/3838. By analyzing the setup in Snuba [devserver](https://github.com/getsentry/snuba/blob/master/snuba/cli/devserver.py), I've confirmed that in the current setup, self-hosted never acts on a generic metric subscription. I cannot be certain if this is a complete solution to the problem, but I do know it fixed the metric alerts for me. 
Proof:
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, …
> fix: add schedulers for generic metrics subscriptions

- sentry/sentry.conf.example.py
As a follow up for https://github.com/getsentry/self-hosted/pull/3837#issuecomment-3130638413
> chore(features): cleanup feature flags grouped by its' category

- install/ensure-correct-permissions-profiles-dir.sh
Fixes #3841 
Check if the parent directory of /var/vroom/sentry-profiles is already owned by vroom:vroom.
- If it is, do nothing.
- If owner is incorrect, correct it
> fix(enhancement): ensure correct ownership check before setting permissions of profiles

- install/ensure-correct-permissions-profiles-dir.sh
- scripts/bump-version.sh
- scripts/post-release.sh
- sentry-admin.sh
Updates the shebang to use `#!/usr/bin/env bash` for improved portability. This ensures that the script uses the `bash` interpreter found in the user's environment, rather than relying on a hardcoded path.
> fix(scripts): use `env` to find `bash` interpreter

- _integration-test/test_01_basics.py
We're going to need https://github.com/getsentry/relay/pull/5055 in order for this to work.
> fix(eap): Fix dataset parameter to target spans

- docker-compose.yml
- sentry/sentry.conf.example.py
Along with getsentry/sentry#99374 and this change taskworkers will be enabled by default in self-hosted. I've left the celery workers active to smooth over any tasks that are in-flight during an upgrade.
Add a worker healtcheck as we have one now.
Refs STREAM-450
> feat(tasks): Remove taskworker option override and add worker healthcheck

- sentry/sentry.conf.example.py
Corresponding PR: https://github.com/getsentry/sentry/pull/99281
> docs: provide information for SENTRY_AIR_GAP flag on Django config file

- docker-compose.yml
- sentry/sentry.conf.example.py
These are replaced by the `taskworker` and `taskscheduler` containers
Refs STREAM-433
> chore(tasks): Remove the worker and cron containers
